# Single source of truth for stat scale definitions.
# Frontend reads the TS version generated by `make stats-scales`.
# ZERO imports from dqt — this file must import nothing from this package.
from typing import Literal, NamedTuple


class StatScale(NamedTuple):
    slug: str
    max: float
    warn_threshold: float
    fail_threshold: float
    direction: Literal["lower_is_better", "higher_is_better"]
    plain_english_label: str
    hint: str


STAT_SCALES: dict[str, StatScale] = {
    s.slug: s for s in [
        StatScale("completeness_rate",         1.0,   0.95,  0.90,  "higher_is_better", "Completeness",               "Fraction of non-null values"),
        StatScale("uniqueness_rate",            1.0,   0.95,  0.80,  "higher_is_better", "Uniqueness",                 "Fraction of distinct values"),
        StatScale("validity_rate",              1.0,   0.95,  0.90,  "higher_is_better", "Validity",                   "Fraction of values matching the rule"),
        StatScale("numeric_mean_shift",        10.0,   2.0,   3.0,   "lower_is_better",  "Mean shift (σ)",             "Z-score of mean deviation from baseline"),
        StatScale("volume_change_ratio",        1.0,   0.10,  0.25,  "lower_is_better",  "Row-count change",           "Fractional deviation from baseline row count"),
        StatScale("schema_change",              1.0,   0.5,   0.5,   "lower_is_better",  "Schema change",              "1.0 if schema changed, 0.0 if unchanged"),
        StatScale("max_in_range",               1.0,   0.5,   0.5,   "lower_is_better",  "Max in bounds",              "1.0 when MAX(col) outside [min, max]; 0.0 otherwise"),
        StatScale("min_in_range",               1.0,   0.5,   0.5,   "lower_is_better",  "Min in bounds",              "1.0 when MIN(col) outside [min, max]; 0.0 otherwise"),
        StatScale("median_in_range",            1.0,   0.5,   0.5,   "lower_is_better",  "Median in bounds",           "1.0 when median outside [min, max]"),
        StatScale("stddev_in_range",            1.0,   0.5,   0.5,   "lower_is_better",  "Stddev in bounds",           "1.0 when STDDEV outside [min, max]"),
        StatScale("sum_in_range",               1.0,   0.5,   0.5,   "lower_is_better",  "Sum in bounds",              "1.0 when SUM outside [min, max]"),
        StatScale("cardinality_in_range",       1.0,   0.5,   0.5,   "lower_is_better",  "Cardinality in bounds",      "1.0 when COUNT(DISTINCT col) outside [min, max]"),
        StatScale("quantile_in_range",          1.0,   0.5,   0.5,   "lower_is_better",  "Quantile in bounds",         "1.0 when specified quantile outside [min, max]"),
        StatScale("value_in_range_violation",   0.10,  0.001, 0.01,  "lower_is_better",  "Values in range",            "Fraction of values outside [min, max]"),
        StatScale("set_membership_violation",   0.10,  0.001, 0.01,  "lower_is_better",  "Set membership",             "Fraction of values not in the allowed set"),
        StatScale("set_exclusion_violation",    0.10,  0.001, 0.01,  "lower_is_better",  "Set exclusion",              "Fraction of values in the forbidden set"),
        StatScale("regex_match_violation",      0.10,  0.001, 0.01,  "lower_is_better",  "Regex format",               "Fraction of values not matching any regex pattern"),
        StatScale("string_length_violation",    0.10,  0.001, 0.01,  "lower_is_better",  "String length",              "Fraction of values with length outside [min_len, max_len]"),
        StatScale("date_format_violation",      0.10,  0.001, 0.01,  "lower_is_better",  "Date format",                "Fraction of values not parseable as the given date format"),
        StatScale("monotonicity_violation",     1.0,   0.5,   0.5,   "lower_is_better",  "Monotonicity",               "1.0 if ordering violated; 0.0 if sequence is monotonic"),
        StatScale("column_pair_violation",      0.10,  0.001, 0.01,  "lower_is_better",  "Column pair rule",           "Fraction of rows where the pair comparison rule is violated"),
        StatScale("composite_uniqueness_violation", 0.10, 0.001, 0.01, "lower_is_better","Composite key uniqueness",   "Fraction of rows that are duplicates on the composite key"),
        StatScale("referential_integrity_rate", 1.0,   0.99,  0.95,  "higher_is_better", "Referential integrity",      "Fraction of FK values present in parent table"),
        StatScale("ks_pvalue",                  1.0,   0.95,  0.99,  "lower_is_better",  "KS drift (1−p)",             "1 − p-value from two-sample KS test; warn p<0.05, fail p<0.01"),
        StatScale("mad_outlier_fraction",       0.20,  0.01,  0.05,  "lower_is_better",  "Outlier fraction (MAD)",        "Fraction of values with |modified Z| > 3.5"),
        StatScale("double_mad_outlier_fraction", 0.20, 0.01,  0.05,  "lower_is_better",  "Outlier fraction (double-MAD)",    "Fraction flagged by asymmetric double-MAD; robust on skewed distributions"),
        StatScale("zscore_outlier_fraction",     0.10, 0.01,  0.05,  "lower_is_better",  "Outlier fraction (Z-score)",       "Fraction of values with |Z| > threshold; valid only under normality"),
        StatScale("adjusted_boxplot_fraction",   0.20, 0.01,  0.05,  "lower_is_better",  "Outlier fraction (adj. boxplot)",  "Fraction outside medcouple-adjusted Tukey fences; Hubert & Vandervieren 2008"),
        StatScale("isolation_forest_fraction",  0.20,  0.05,  0.10,  "lower_is_better",  "Outlier fraction (IF)",      "Fraction of rows classified as anomalies by Isolation Forest"),
        StatScale("stl_residual_zscore",       10.0,   3.0,   5.0,   "lower_is_better",  "STL residual Z-score",       "Max absolute Z-score of STL residuals over the current window"),
    ]
}
