# Single source of truth for stat scale definitions.
# Frontend reads the TS version generated by `make stats-scales`.
# ZERO imports from dqt — this file must import nothing from this package.
from typing import Literal, NamedTuple


class StatScale(NamedTuple):
    slug: str
    max: float
    warn_threshold: float
    fail_threshold: float
    direction: Literal["lower_is_better", "higher_is_better"]
    plain_english_label: str
    hint: str


STAT_SCALES: dict[str, StatScale] = {
    s.slug: s for s in [
        StatScale("completeness_rate",         1.0,   0.95,  0.90,  "higher_is_better", "Completeness",               "Fraction of non-null values"),
        StatScale("uniqueness_rate",            1.0,   0.95,  0.80,  "higher_is_better", "Uniqueness",                 "Fraction of distinct values"),
        StatScale("validity_rate",              1.0,   0.95,  0.90,  "higher_is_better", "Validity",                   "Fraction of values matching the rule"),
        StatScale("numeric_mean_shift",        10.0,   2.0,   3.0,   "lower_is_better",  "Mean shift (σ)",             "Z-score of mean deviation from baseline"),
        StatScale("volume_change_ratio",        1.0,   0.10,  0.25,  "lower_is_better",  "Row-count change",           "Fractional deviation from baseline row count"),
        StatScale("schema_change",              1.0,   0.5,   0.5,   "lower_is_better",  "Schema change",              "1.0 if schema changed, 0.0 if unchanged"),
        StatScale("max_in_range",               1.0,   0.5,   0.5,   "lower_is_better",  "Max in bounds",              "1.0 when MAX(col) outside [min, max]; 0.0 otherwise"),
        StatScale("min_in_range",               1.0,   0.5,   0.5,   "lower_is_better",  "Min in bounds",              "1.0 when MIN(col) outside [min, max]; 0.0 otherwise"),
        StatScale("median_in_range",            1.0,   0.5,   0.5,   "lower_is_better",  "Median in bounds",           "1.0 when median outside [min, max]"),
        StatScale("stddev_in_range",            1.0,   0.5,   0.5,   "lower_is_better",  "Stddev in bounds",           "1.0 when STDDEV outside [min, max]"),
        StatScale("sum_in_range",               1.0,   0.5,   0.5,   "lower_is_better",  "Sum in bounds",              "1.0 when SUM outside [min, max]"),
        StatScale("cardinality_in_range",       1.0,   0.5,   0.5,   "lower_is_better",  "Cardinality in bounds",      "1.0 when COUNT(DISTINCT col) outside [min, max]"),
        StatScale("quantile_in_range",          1.0,   0.5,   0.5,   "lower_is_better",  "Quantile in bounds",         "1.0 when specified quantile outside [min, max]"),
        StatScale("value_in_range_violation",   0.10,  0.001, 0.01,  "lower_is_better",  "Values in range",            "Fraction of values outside [min, max]"),
        StatScale("set_membership_violation",   0.10,  0.001, 0.01,  "lower_is_better",  "Set membership",             "Fraction of values not in the allowed set"),
        StatScale("set_exclusion_violation",    0.10,  0.001, 0.01,  "lower_is_better",  "Set exclusion",              "Fraction of values in the forbidden set"),
        StatScale("regex_match_violation",      0.10,  0.001, 0.01,  "lower_is_better",  "Regex format",               "Fraction of values not matching any regex pattern"),
        StatScale("string_length_violation",    0.10,  0.001, 0.01,  "lower_is_better",  "String length",              "Fraction of values with length outside [min_len, max_len]"),
        StatScale("date_format_violation",      0.10,  0.001, 0.01,  "lower_is_better",  "Date format",                "Fraction of values not parseable as the given date format"),
        StatScale("monotonicity_violation",     1.0,   0.5,   0.5,   "lower_is_better",  "Monotonicity",               "1.0 if ordering violated; 0.0 if sequence is monotonic"),
        StatScale("column_pair_violation",      0.10,  0.001, 0.01,  "lower_is_better",  "Column pair rule",           "Fraction of rows where the pair comparison rule is violated"),
        StatScale("composite_uniqueness_violation", 0.10, 0.001, 0.01, "lower_is_better","Composite key uniqueness",   "Fraction of rows that are duplicates on the composite key"),
        StatScale("referential_integrity_rate", 1.0,   0.99,  0.95,  "higher_is_better", "Referential integrity",      "Fraction of FK values present in parent table"),
        StatScale("ks_pvalue",                  1.0,   0.95,  0.99,  "lower_is_better",  "KS drift (1−p)",             "1 − p-value from two-sample KS test; warn p<0.05, fail p<0.01"),
        StatScale("mad_outlier_fraction",       0.20,  0.01,  0.05,  "lower_is_better",  "Outlier fraction (MAD)",        "Fraction of values with |modified Z| > 3.5"),
        StatScale("double_mad_outlier_fraction", 0.20, 0.01,  0.05,  "lower_is_better",  "Outlier fraction (double-MAD)",    "Fraction flagged by asymmetric double-MAD; robust on skewed distributions"),
        StatScale("zscore_outlier_fraction",     0.10, 0.01,  0.05,  "lower_is_better",  "Outlier fraction (Z-score)",       "Fraction of values with |Z| > threshold; valid only under normality"),
        StatScale("adjusted_boxplot_fraction",   0.20, 0.01,  0.05,  "lower_is_better",  "Outlier fraction (adj. boxplot)",  "Fraction outside medcouple-adjusted Tukey fences; Hubert & Vandervieren 2008"),
        StatScale("isolation_forest_fraction",  0.20,  0.05,  0.10,  "lower_is_better",  "Outlier fraction (IF)",      "Fraction of rows classified as anomalies by Isolation Forest"),
        StatScale("stl_residual_zscore",       10.0,   3.0,   5.0,   "lower_is_better",  "STL residual Z-score",       "Max absolute Z-score of STL residuals over the current window"),
        StatScale("freshness_seconds_behind", 86400*7, 3600, 86400, "lower_is_better",
                  "Data freshness", "Seconds since the most recent row timestamp"),
        StatScale("null_fraction", 1.0, 0.01, 0.05, "lower_is_better",
                  "Null fraction", "Fraction of rows where the column is NULL"),
        StatScale("string_case_violation", 1.0, 0.001, 0.01, "lower_is_better",
                  "String case violation", "Fraction of rows with wrong case"),
        StatScale("sql_assertion_violation", 1.0, 0.001, 0.01, "lower_is_better",
                  "SQL assertion violation", "Fraction of rows failing the custom SQL condition"),
        StatScale("date_part_missing_fraction", 1.0, 0.01, 0.05, "lower_is_better",
                  "Date-part completeness", "Fraction of expected date buckets with no data"),
        StatScale("outlier_fraction_drift", 1.0, 0.001, 0.01, "lower_is_better",
                  "Outlier fraction drift", "Deviation of current outlier fraction from historical baseline range"),
        StatScale("row_count_in_range", 1.0, 0.5, 0.5, "lower_is_better",
                  "Row count in range", "1.0 if row count in the date window is outside [min_rows, max_rows]; 0.0 if within range"),
        StatScale("iqr_fence",           0.20, 0.01,  0.05,  "lower_is_better", "Outlier fraction (IQR)",          "Fraction of values outside Tukey IQR fences; k=1.5 by default"),
        StatScale("grubbs",              1.0,  0.95,  0.99,  "lower_is_better", "Grubbs outlier (1−p)",            "1 − p-value from Grubbs test; warn p<0.05, fail p<0.01"),
        StatScale("generalized_esd",     0.10, 0.01,  0.05,  "lower_is_better", "Outlier fraction (GESD)",         "Fraction of outliers found by Generalized ESD (Rosner 1983)"),
        StatScale("wasserstein_1",       10.0, 0.20,  0.50,  "lower_is_better", "Wasserstein-1 (norm.)",           "Earth-mover distance normalized by reference std; 0.2=moderate shift, 0.5=large"),
        StatScale("psi",                 2.0,  0.10,  0.20,  "lower_is_better", "Population Stability Index",      "PSI<0.1 stable, 0.1–0.2 moderate shift, >0.2 significant population shift"),
        StatScale("kl_divergence",       5.0,  0.10,  0.30,  "lower_is_better", "KL divergence",                   "Kullback–Leibler divergence (binned); 0=identical distributions"),
        StatScale("js_divergence",       1.0,  0.10,  0.20,  "lower_is_better", "Jensen-Shannon distance",         "JS distance (bounded [0,1]); 0=identical, 1=maximally different"),
        StatScale("chi_square_drift",    1.0,  0.95,  0.99,  "lower_is_better", "Chi-square drift (1−p)",          "1 − p-value from chi-square test for categorical drift; warn p<0.05, fail p<0.01"),
        StatScale("cramers_v",           1.0,  0.15,  0.30,  "lower_is_better", "Cramér's V (drift)",              "V from 2×k contingency table; 0=no drift, 1=maximum categorical drift"),
        StatScale("benford_law_fit",     1.0,  0.95,  0.99,  "lower_is_better", "Benford's Law fit (1−p)",         "1 − p-value from chi-square vs expected first-digit frequencies"),
    ]
}
