[phases.setup]
nixPkgs = ["python312", "uv"]

[phases.install]
cmds = [
  "uv venv",
  "uv pip install --python .venv/bin/python ."
]

[start]
cmd = ".venv/bin/uvicorn dqt_server.main:app --host 0.0.0.0 --port $PORT"
