"""Reference data seed: ISO 3166-2 first-level administrative subdivisions."""
from __future__ import annotations

# (code, country_alpha2, name, category)
# Covers ~30 high-traffic countries; ~1,100 entries total.
ISO_REGIONS = [
    # United States -- 50 states + DC + 5 territories
    ("US-AL", "US", "Alabama", "state"), ("US-AK", "US", "Alaska", "state"),
    ("US-AZ", "US", "Arizona", "state"), ("US-AR", "US", "Arkansas", "state"),
    ("US-CA", "US", "California", "state"), ("US-CO", "US", "Colorado", "state"),
    ("US-CT", "US", "Connecticut", "state"), ("US-DE", "US", "Delaware", "state"),
    ("US-FL", "US", "Florida", "state"), ("US-GA", "US", "Georgia", "state"),
    ("US-HI", "US", "Hawaii", "state"), ("US-ID", "US", "Idaho", "state"),
    ("US-IL", "US", "Illinois", "state"), ("US-IN", "US", "Indiana", "state"),
    ("US-IA", "US", "Iowa", "state"), ("US-KS", "US", "Kansas", "state"),
    ("US-KY", "US", "Kentucky", "state"), ("US-LA", "US", "Louisiana", "state"),
    ("US-ME", "US", "Maine", "state"), ("US-MD", "US", "Maryland", "state"),
    ("US-MA", "US", "Massachusetts", "state"), ("US-MI", "US", "Michigan", "state"),
    ("US-MN", "US", "Minnesota", "state"), ("US-MS", "US", "Mississippi", "state"),
    ("US-MO", "US", "Missouri", "state"), ("US-MT", "US", "Montana", "state"),
    ("US-NE", "US", "Nebraska", "state"), ("US-NV", "US", "Nevada", "state"),
    ("US-NH", "US", "New Hampshire", "state"), ("US-NJ", "US", "New Jersey", "state"),
    ("US-NM", "US", "New Mexico", "state"), ("US-NY", "US", "New York", "state"),
    ("US-NC", "US", "North Carolina", "state"), ("US-ND", "US", "North Dakota", "state"),
    ("US-OH", "US", "Ohio", "state"), ("US-OK", "US", "Oklahoma", "state"),
    ("US-OR", "US", "Oregon", "state"), ("US-PA", "US", "Pennsylvania", "state"),
    ("US-RI", "US", "Rhode Island", "state"), ("US-SC", "US", "South Carolina", "state"),
    ("US-SD", "US", "South Dakota", "state"), ("US-TN", "US", "Tennessee", "state"),
    ("US-TX", "US", "Texas", "state"), ("US-UT", "US", "Utah", "state"),
    ("US-VT", "US", "Vermont", "state"), ("US-VA", "US", "Virginia", "state"),
    ("US-WA", "US", "Washington", "state"), ("US-WV", "US", "West Virginia", "state"),
    ("US-WI", "US", "Wisconsin", "state"), ("US-WY", "US", "Wyoming", "state"),
    ("US-DC", "US", "District of Columbia", "district"),
    ("US-AS", "US", "American Samoa", "territory"), ("US-GU", "US", "Guam", "territory"),
    ("US-MP", "US", "Northern Mariana Islands", "territory"),
    ("US-PR", "US", "Puerto Rico", "territory"), ("US-VI", "US", "U.S. Virgin Islands", "territory"),
    # Canada -- 10 provinces + 3 territories
    ("CA-AB", "CA", "Alberta", "province"), ("CA-BC", "CA", "British Columbia", "province"),
    ("CA-MB", "CA", "Manitoba", "province"), ("CA-NB", "CA", "New Brunswick", "province"),
    ("CA-NL", "CA", "Newfoundland and Labrador", "province"), ("CA-NS", "CA", "Nova Scotia", "province"),
    ("CA-ON", "CA", "Ontario", "province"), ("CA-PE", "CA", "Prince Edward Island", "province"),
    ("CA-QC", "CA", "Quebec", "province"), ("CA-SK", "CA", "Saskatchewan", "province"),
    ("CA-NT", "CA", "Northwest Territories", "territory"), ("CA-NU", "CA", "Nunavut", "territory"),
    ("CA-YT", "CA", "Yukon", "territory"),
    # Australia -- 6 states + 2 territories
    ("AU-ACT", "AU", "Australian Capital Territory", "territory"),
    ("AU-NSW", "AU", "New South Wales", "state"), ("AU-NT", "AU", "Northern Territory", "territory"),
    ("AU-QLD", "AU", "Queensland", "state"), ("AU-SA", "AU", "South Australia", "state"),
    ("AU-TAS", "AU", "Tasmania", "state"), ("AU-VIC", "AU", "Victoria", "state"),
    ("AU-WA", "AU", "Western Australia", "state"),
    # United Kingdom
    ("GB-ENG", "GB", "England", "country"), ("GB-NIR", "GB", "Northern Ireland", "province"),
    ("GB-SCT", "GB", "Scotland", "country"), ("GB-WLS", "GB", "Wales", "country"),
    # Germany -- 16 Bundeslander
    ("DE-BB", "DE", "Brandenburg", "state"), ("DE-BE", "DE", "Berlin", "state"),
    ("DE-BW", "DE", "Baden-Wurttemberg", "state"), ("DE-BY", "DE", "Bavaria", "state"),
    ("DE-HB", "DE", "Bremen", "state"), ("DE-HE", "DE", "Hesse", "state"),
    ("DE-HH", "DE", "Hamburg", "state"), ("DE-MV", "DE", "Mecklenburg-Vorpommern", "state"),
    ("DE-NI", "DE", "Lower Saxony", "state"), ("DE-NW", "DE", "North Rhine-Westphalia", "state"),
    ("DE-RP", "DE", "Rhineland-Palatinate", "state"), ("DE-SH", "DE", "Schleswig-Holstein", "state"),
    ("DE-SL", "DE", "Saarland", "state"), ("DE-SN", "DE", "Saxony", "state"),
    ("DE-ST", "DE", "Saxony-Anhalt", "state"), ("DE-TH", "DE", "Thuringia", "state"),
    # France -- 13 metropolitan + 5 overseas
    ("FR-ARA", "FR", "Auvergne-Rhone-Alpes", "region"), ("FR-BFC", "FR", "Bourgogne-Franche-Comte", "region"),
    ("FR-BRE", "FR", "Bretagne", "region"), ("FR-CVL", "FR", "Centre-Val de Loire", "region"),
    ("FR-COR", "FR", "Corse", "region"), ("FR-GES", "FR", "Grand Est", "region"),
    ("FR-HDF", "FR", "Hauts-de-France", "region"), ("FR-IDF", "FR", "Ile-de-France", "region"),
    ("FR-NOR", "FR", "Normandie", "region"), ("FR-NAQ", "FR", "Nouvelle-Aquitaine", "region"),
    ("FR-OCC", "FR", "Occitanie", "region"), ("FR-PDL", "FR", "Pays de la Loire", "region"),
    ("FR-PAC", "FR", "Provence-Alpes-Cote d'Azur", "region"),
    ("FR-GUA", "FR", "Guadeloupe", "overseas region"), ("FR-GUF", "FR", "French Guiana", "overseas region"),
    ("FR-MTQ", "FR", "Martinique", "overseas region"), ("FR-LRE", "FR", "La Reunion", "overseas region"),
    ("FR-MYT", "FR", "Mayotte", "overseas region"),
    # Brazil -- 26 states + DF
    ("BR-AC", "BR", "Acre", "state"), ("BR-AL", "BR", "Alagoas", "state"),
    ("BR-AP", "BR", "Amapa", "state"), ("BR-AM", "BR", "Amazonas", "state"),
    ("BR-BA", "BR", "Bahia", "state"), ("BR-CE", "BR", "Ceara", "state"),
    ("BR-DF", "BR", "Distrito Federal", "federal district"), ("BR-ES", "BR", "Espirito Santo", "state"),
    ("BR-GO", "BR", "Goias", "state"), ("BR-MA", "BR", "Maranhao", "state"),
    ("BR-MT", "BR", "Mato Grosso", "state"), ("BR-MS", "BR", "Mato Grosso do Sul", "state"),
    ("BR-MG", "BR", "Minas Gerais", "state"), ("BR-PA", "BR", "Para", "state"),
    ("BR-PB", "BR", "Paraiba", "state"), ("BR-PR", "BR", "Parana", "state"),
    ("BR-PE", "BR", "Pernambuco", "state"), ("BR-PI", "BR", "Piaui", "state"),
    ("BR-RJ", "BR", "Rio de Janeiro", "state"), ("BR-RN", "BR", "Rio Grande do Norte", "state"),
    ("BR-RS", "BR", "Rio Grande do Sul", "state"), ("BR-RO", "BR", "Rondonia", "state"),
    ("BR-RR", "BR", "Roraima", "state"), ("BR-SC", "BR", "Santa Catarina", "state"),
    ("BR-SP", "BR", "Sao Paulo", "state"), ("BR-SE", "BR", "Sergipe", "state"),
    ("BR-TO", "BR", "Tocantins", "state"),
    # Mexico -- 31 states + CDMX
    ("MX-AGU", "MX", "Aguascalientes", "state"), ("MX-BCN", "MX", "Baja California", "state"),
    ("MX-BCS", "MX", "Baja California Sur", "state"), ("MX-CAM", "MX", "Campeche", "state"),
    ("MX-CHP", "MX", "Chiapas", "state"), ("MX-CHH", "MX", "Chihuahua", "state"),
    ("MX-CMX", "MX", "Ciudad de Mexico", "federal entity"), ("MX-COA", "MX", "Coahuila", "state"),
    ("MX-COL", "MX", "Colima", "state"), ("MX-DUR", "MX", "Durango", "state"),
    ("MX-GUA", "MX", "Guanajuato", "state"), ("MX-GRO", "MX", "Guerrero", "state"),
    ("MX-HID", "MX", "Hidalgo", "state"), ("MX-JAL", "MX", "Jalisco", "state"),
    ("MX-MEX", "MX", "Mexico", "state"), ("MX-MIC", "MX", "Michoacan", "state"),
    ("MX-MOR", "MX", "Morelos", "state"), ("MX-NAY", "MX", "Nayarit", "state"),
    ("MX-NLE", "MX", "Nuevo Leon", "state"), ("MX-OAX", "MX", "Oaxaca", "state"),
    ("MX-PUE", "MX", "Puebla", "state"), ("MX-QUE", "MX", "Queretaro", "state"),
    ("MX-ROO", "MX", "Quintana Roo", "state"), ("MX-SLP", "MX", "San Luis Potosi", "state"),
    ("MX-SIN", "MX", "Sinaloa", "state"), ("MX-SON", "MX", "Sonora", "state"),
    ("MX-TAB", "MX", "Tabasco", "state"), ("MX-TAM", "MX", "Tamaulipas", "state"),
    ("MX-TLA", "MX", "Tlaxcala", "state"), ("MX-VER", "MX", "Veracruz", "state"),
    ("MX-YUC", "MX", "Yucatan", "state"), ("MX-ZAC", "MX", "Zacatecas", "state"),
    # Spain -- 17 autonomous communities + 2 autonomous cities
    ("ES-AN", "ES", "Andalusia", "autonomous community"), ("ES-AR", "ES", "Aragon", "autonomous community"),
    ("ES-AS", "ES", "Asturias", "autonomous community"), ("ES-CN", "ES", "Canary Islands", "autonomous community"),
    ("ES-CB", "ES", "Cantabria", "autonomous community"), ("ES-CM", "ES", "Castile-La Mancha", "autonomous community"),
    ("ES-CL", "ES", "Castile and Leon", "autonomous community"), ("ES-CT", "ES", "Catalonia", "autonomous community"),
    ("ES-CE", "ES", "Ceuta", "autonomous city"), ("ES-EX", "ES", "Extremadura", "autonomous community"),
    ("ES-GA", "ES", "Galicia", "autonomous community"), ("ES-RI", "ES", "La Rioja", "autonomous community"),
    ("ES-MD", "ES", "Madrid", "autonomous community"), ("ES-ML", "ES", "Melilla", "autonomous city"),
    ("ES-MC", "ES", "Murcia", "autonomous community"), ("ES-NC", "ES", "Navarre", "autonomous community"),
    ("ES-PV", "ES", "Basque Country", "autonomous community"), ("ES-VC", "ES", "Valencian Community", "autonomous community"),
    # Italy -- 20 regions
    ("IT-65", "IT", "Abruzzo", "region"), ("IT-77", "IT", "Basilicata", "region"),
    ("IT-78", "IT", "Calabria", "region"), ("IT-72", "IT", "Campania", "region"),
    ("IT-45", "IT", "Emilia-Romagna", "region"), ("IT-36", "IT", "Friuli-Venezia Giulia", "region"),
    ("IT-62", "IT", "Lazio", "region"), ("IT-42", "IT", "Liguria", "region"),
    ("IT-25", "IT", "Lombardy", "region"), ("IT-57", "IT", "Marche", "region"),
    ("IT-67", "IT", "Molise", "region"), ("IT-21", "IT", "Piedmont", "region"),
    ("IT-75", "IT", "Apulia", "region"), ("IT-88", "IT", "Sardinia", "region"),
    ("IT-82", "IT", "Sicily", "region"), ("IT-52", "IT", "Tuscany", "region"),
    ("IT-32", "IT", "Trentino-South Tyrol", "region"), ("IT-55", "IT", "Umbria", "region"),
    ("IT-23", "IT", "Aosta Valley", "region"), ("IT-34", "IT", "Veneto", "region"),
    # Japan -- 47 prefectures
    ("JP-01", "JP", "Hokkaido", "prefecture"), ("JP-02", "JP", "Aomori", "prefecture"),
    ("JP-03", "JP", "Iwate", "prefecture"), ("JP-04", "JP", "Miyagi", "prefecture"),
    ("JP-05", "JP", "Akita", "prefecture"), ("JP-06", "JP", "Yamagata", "prefecture"),
    ("JP-07", "JP", "Fukushima", "prefecture"), ("JP-08", "JP", "Ibaraki", "prefecture"),
    ("JP-09", "JP", "Tochigi", "prefecture"), ("JP-10", "JP", "Gunma", "prefecture"),
    ("JP-11", "JP", "Saitama", "prefecture"), ("JP-12", "JP", "Chiba", "prefecture"),
    ("JP-13", "JP", "Tokyo", "prefecture"), ("JP-14", "JP", "Kanagawa", "prefecture"),
    ("JP-15", "JP", "Niigata", "prefecture"), ("JP-16", "JP", "Toyama", "prefecture"),
    ("JP-17", "JP", "Ishikawa", "prefecture"), ("JP-18", "JP", "Fukui", "prefecture"),
    ("JP-19", "JP", "Yamanashi", "prefecture"), ("JP-20", "JP", "Nagano", "prefecture"),
    ("JP-21", "JP", "Gifu", "prefecture"), ("JP-22", "JP", "Shizuoka", "prefecture"),
    ("JP-23", "JP", "Aichi", "prefecture"), ("JP-24", "JP", "Mie", "prefecture"),
    ("JP-25", "JP", "Shiga", "prefecture"), ("JP-26", "JP", "Kyoto", "prefecture"),
    ("JP-27", "JP", "Osaka", "prefecture"), ("JP-28", "JP", "Hyogo", "prefecture"),
    ("JP-29", "JP", "Nara", "prefecture"), ("JP-30", "JP", "Wakayama", "prefecture"),
    ("JP-31", "JP", "Tottori", "prefecture"), ("JP-32", "JP", "Shimane", "prefecture"),
    ("JP-33", "JP", "Okayama", "prefecture"), ("JP-34", "JP", "Hiroshima", "prefecture"),
    ("JP-35", "JP", "Yamaguchi", "prefecture"), ("JP-36", "JP", "Tokushima", "prefecture"),
    ("JP-37", "JP", "Kagawa", "prefecture"), ("JP-38", "JP", "Ehime", "prefecture"),
    ("JP-39", "JP", "Kochi", "prefecture"), ("JP-40", "JP", "Fukuoka", "prefecture"),
    ("JP-41", "JP", "Saga", "prefecture"), ("JP-42", "JP", "Nagasaki", "prefecture"),
    ("JP-43", "JP", "Kumamoto", "prefecture"), ("JP-44", "JP", "Oita", "prefecture"),
    ("JP-45", "JP", "Miyazaki", "prefecture"), ("JP-46", "JP", "Kagoshima", "prefecture"),
    ("JP-47", "JP", "Okinawa", "prefecture"),
    # India -- 28 states + 8 union territories
    ("IN-AN", "IN", "Andaman and Nicobar Islands", "union territory"),
    ("IN-AP", "IN", "Andhra Pradesh", "state"), ("IN-AR", "IN", "Arunachal Pradesh", "state"),
    ("IN-AS", "IN", "Assam", "state"), ("IN-BR", "IN", "Bihar", "state"),
    ("IN-CH", "IN", "Chandigarh", "union territory"), ("IN-CT", "IN", "Chhattisgarh", "state"),
    ("IN-DN", "IN", "Dadra and Nagar Haveli and Daman and Diu", "union territory"),
    ("IN-DL", "IN", "Delhi", "union territory"), ("IN-GA", "IN", "Goa", "state"),
    ("IN-GJ", "IN", "Gujarat", "state"), ("IN-HR", "IN", "Haryana", "state"),
    ("IN-HP", "IN", "Himachal Pradesh", "state"), ("IN-JK", "IN", "Jammu and Kashmir", "union territory"),
    ("IN-JH", "IN", "Jharkhand", "state"), ("IN-KA", "IN", "Karnataka", "state"),
    ("IN-KL", "IN", "Kerala", "state"), ("IN-LA", "IN", "Ladakh", "union territory"),
    ("IN-LD", "IN", "Lakshadweep", "union territory"), ("IN-MP", "IN", "Madhya Pradesh", "state"),
    ("IN-MH", "IN", "Maharashtra", "state"), ("IN-MN", "IN", "Manipur", "state"),
    ("IN-ML", "IN", "Meghalaya", "state"), ("IN-MZ", "IN", "Mizoram", "state"),
    ("IN-NL", "IN", "Nagaland", "state"), ("IN-OR", "IN", "Odisha", "state"),
    ("IN-PY", "IN", "Puducherry", "union territory"), ("IN-PB", "IN", "Punjab", "state"),
    ("IN-RJ", "IN", "Rajasthan", "state"), ("IN-SK", "IN", "Sikkim", "state"),
    ("IN-TN", "IN", "Tamil Nadu", "state"), ("IN-TG", "IN", "Telangana", "state"),
    ("IN-TR", "IN", "Tripura", "state"), ("IN-UP", "IN", "Uttar Pradesh", "state"),
    ("IN-UT", "IN", "Uttarakhand", "state"), ("IN-WB", "IN", "West Bengal", "state"),
    # China -- 23 provinces + 5 autonomous regions + 4 municipalities + 2 SARs
    ("CN-AH", "CN", "Anhui", "province"), ("CN-BJ", "CN", "Beijing", "municipality"),
    ("CN-CQ", "CN", "Chongqing", "municipality"), ("CN-FJ", "CN", "Fujian", "province"),
    ("CN-GS", "CN", "Gansu", "province"), ("CN-GD", "CN", "Guangdong", "province"),
    ("CN-GX", "CN", "Guangxi", "autonomous region"), ("CN-GZ", "CN", "Guizhou", "province"),
    ("CN-HI", "CN", "Hainan", "province"), ("CN-HE", "CN", "Hebei", "province"),
    ("CN-HL", "CN", "Heilongjiang", "province"), ("CN-HA", "CN", "Henan", "province"),
    ("CN-HK", "CN", "Hong Kong", "special administrative region"),
    ("CN-HB", "CN", "Hubei", "province"), ("CN-HN", "CN", "Hunan", "province"),
    ("CN-NM", "CN", "Inner Mongolia", "autonomous region"), ("CN-JS", "CN", "Jiangsu", "province"),
    ("CN-JX", "CN", "Jiangxi", "province"), ("CN-JL", "CN", "Jilin", "province"),
    ("CN-LN", "CN", "Liaoning", "province"), ("CN-MO", "CN", "Macau", "special administrative region"),
    ("CN-NX", "CN", "Ningxia", "autonomous region"), ("CN-QH", "CN", "Qinghai", "province"),
    ("CN-SN", "CN", "Shaanxi", "province"), ("CN-SD", "CN", "Shandong", "province"),
    ("CN-SH", "CN", "Shanghai", "municipality"), ("CN-SX", "CN", "Shanxi", "province"),
    ("CN-SC", "CN", "Sichuan", "province"), ("CN-TJ", "CN", "Tianjin", "municipality"),
    ("CN-XJ", "CN", "Xinjiang", "autonomous region"), ("CN-XZ", "CN", "Tibet", "autonomous region"),
    ("CN-YN", "CN", "Yunnan", "province"), ("CN-ZJ", "CN", "Zhejiang", "province"),
    # Russia -- 85 federal subjects
    ("RU-AD", "RU", "Adygea", "republic"), ("RU-AL", "RU", "Altai Republic", "republic"),
    ("RU-ALT", "RU", "Altai Krai", "krai"), ("RU-AMU", "RU", "Amur Oblast", "oblast"),
    ("RU-ARK", "RU", "Arkhangelsk Oblast", "oblast"), ("RU-AST", "RU", "Astrakhan Oblast", "oblast"),
    ("RU-BA", "RU", "Bashkortostan", "republic"), ("RU-BEL", "RU", "Belgorod Oblast", "oblast"),
    ("RU-BRY", "RU", "Bryansk Oblast", "oblast"), ("RU-BU", "RU", "Buryatia", "republic"),
    ("RU-CE", "RU", "Chechnya", "republic"), ("RU-CHE", "RU", "Chelyabinsk Oblast", "oblast"),
    ("RU-CHU", "RU", "Chukotka", "autonomous okrug"), ("RU-CU", "RU", "Chuvashia", "republic"),
    ("RU-DA", "RU", "Dagestan", "republic"), ("RU-IN", "RU", "Ingushetia", "republic"),
    ("RU-IRK", "RU", "Irkutsk Oblast", "oblast"), ("RU-IVA", "RU", "Ivanovo Oblast", "oblast"),
    ("RU-KGD", "RU", "Kaliningrad Oblast", "oblast"), ("RU-KL", "RU", "Kalmykia", "republic"),
    ("RU-KLU", "RU", "Kaluga Oblast", "oblast"), ("RU-KAM", "RU", "Kamchatka Krai", "krai"),
    ("RU-KB", "RU", "Kabardino-Balkaria", "republic"), ("RU-KC", "RU", "Karachay-Cherkessia", "republic"),
    ("RU-KEM", "RU", "Kemerovo Oblast", "oblast"), ("RU-KHA", "RU", "Khabarovsk Krai", "krai"),
    ("RU-KHM", "RU", "Khanty-Mansiysk", "autonomous okrug"), ("RU-KIR", "RU", "Kirov Oblast", "oblast"),
    ("RU-KO", "RU", "Komi", "republic"), ("RU-KOS", "RU", "Kostroma Oblast", "oblast"),
    ("RU-KDA", "RU", "Krasnodar Krai", "krai"), ("RU-KYA", "RU", "Krasnoyarsk Krai", "krai"),
    ("RU-KGN", "RU", "Kurgan Oblast", "oblast"), ("RU-KRS", "RU", "Kursk Oblast", "oblast"),
    ("RU-LEN", "RU", "Leningrad Oblast", "oblast"), ("RU-LIP", "RU", "Lipetsk Oblast", "oblast"),
    ("RU-MAG", "RU", "Magadan Oblast", "oblast"), ("RU-ME", "RU", "Mari El", "republic"),
    ("RU-MO", "RU", "Mordovia", "republic"), ("RU-MOS", "RU", "Moscow Oblast", "oblast"),
    ("RU-MOW", "RU", "Moscow", "federal city"), ("RU-MUR", "RU", "Murmansk Oblast", "oblast"),
    ("RU-NEN", "RU", "Nenets", "autonomous okrug"), ("RU-NIZ", "RU", "Nizhny Novgorod Oblast", "oblast"),
    ("RU-NGR", "RU", "Novgorod Oblast", "oblast"), ("RU-NVS", "RU", "Novosibirsk Oblast", "oblast"),
    ("RU-OMS", "RU", "Omsk Oblast", "oblast"), ("RU-ORE", "RU", "Orenburg Oblast", "oblast"),
    ("RU-ORL", "RU", "Oryol Oblast", "oblast"), ("RU-PNZ", "RU", "Penza Oblast", "oblast"),
    ("RU-PER", "RU", "Perm Krai", "krai"), ("RU-PRI", "RU", "Primorsky Krai", "krai"),
    ("RU-PSK", "RU", "Pskov Oblast", "oblast"), ("RU-ROS", "RU", "Rostov Oblast", "oblast"),
    ("RU-RYA", "RU", "Ryazan Oblast", "oblast"), ("RU-SAK", "RU", "Sakhalin Oblast", "oblast"),
    ("RU-SA", "RU", "Sakha", "republic"), ("RU-SAM", "RU", "Samara Oblast", "oblast"),
    ("RU-SPE", "RU", "Saint Petersburg", "federal city"), ("RU-SAR", "RU", "Saratov Oblast", "oblast"),
    ("RU-SE", "RU", "North Ossetia-Alania", "republic"), ("RU-SMO", "RU", "Smolensk Oblast", "oblast"),
    ("RU-STA", "RU", "Stavropol Krai", "krai"), ("RU-SVE", "RU", "Sverdlovsk Oblast", "oblast"),
    ("RU-TAM", "RU", "Tambov Oblast", "oblast"), ("RU-TA", "RU", "Tatarstan", "republic"),
    ("RU-TOM", "RU", "Tomsk Oblast", "oblast"), ("RU-TUL", "RU", "Tula Oblast", "oblast"),
    ("RU-TYU", "RU", "Tyumen Oblast", "oblast"), ("RU-TY", "RU", "Tuva", "republic"),
    ("RU-UD", "RU", "Udmurtia", "republic"), ("RU-ULY", "RU", "Ulyanovsk Oblast", "oblast"),
    ("RU-VLA", "RU", "Vladimir Oblast", "oblast"), ("RU-VGG", "RU", "Volgograd Oblast", "oblast"),
    ("RU-VLG", "RU", "Vologda Oblast", "oblast"), ("RU-VOR", "RU", "Voronezh Oblast", "oblast"),
    ("RU-YAN", "RU", "Yamalo-Nenets", "autonomous okrug"), ("RU-YAR", "RU", "Yaroslavl Oblast", "oblast"),
    ("RU-ZAB", "RU", "Zabaykalsky Krai", "krai"),
    # South Africa
    ("ZA-EC", "ZA", "Eastern Cape", "province"), ("ZA-FS", "ZA", "Free State", "province"),
    ("ZA-GP", "ZA", "Gauteng", "province"), ("ZA-KZN", "ZA", "KwaZulu-Natal", "province"),
    ("ZA-LP", "ZA", "Limpopo", "province"), ("ZA-MP", "ZA", "Mpumalanga", "province"),
    ("ZA-NW", "ZA", "North West", "province"), ("ZA-NC", "ZA", "Northern Cape", "province"),
    ("ZA-WC", "ZA", "Western Cape", "province"),
    # Argentina
    ("AR-B", "AR", "Buenos Aires Province", "province"), ("AR-C", "AR", "Buenos Aires City", "autonomous city"),
    ("AR-K", "AR", "Catamarca", "province"), ("AR-H", "AR", "Chaco", "province"),
    ("AR-U", "AR", "Chubut", "province"), ("AR-X", "AR", "Cordoba", "province"),
    ("AR-W", "AR", "Corrientes", "province"), ("AR-E", "AR", "Entre Rios", "province"),
    ("AR-P", "AR", "Formosa", "province"), ("AR-Y", "AR", "Jujuy", "province"),
    ("AR-L", "AR", "La Pampa", "province"), ("AR-F", "AR", "La Rioja", "province"),
    ("AR-M", "AR", "Mendoza", "province"), ("AR-N", "AR", "Misiones", "province"),
    ("AR-Q", "AR", "Neuquen", "province"), ("AR-R", "AR", "Rio Negro", "province"),
    ("AR-A", "AR", "Salta", "province"), ("AR-J", "AR", "San Juan", "province"),
    ("AR-D", "AR", "San Luis", "province"), ("AR-Z", "AR", "Santa Cruz", "province"),
    ("AR-S", "AR", "Santa Fe", "province"), ("AR-G", "AR", "Santiago del Estero", "province"),
    ("AR-V", "AR", "Tierra del Fuego", "province"), ("AR-T", "AR", "Tucuman", "province"),
    # Netherlands
    ("NL-DR", "NL", "Drenthe", "province"), ("NL-FL", "NL", "Flevoland", "province"),
    ("NL-FR", "NL", "Friesland", "province"), ("NL-GE", "NL", "Gelderland", "province"),
    ("NL-GR", "NL", "Groningen", "province"), ("NL-LI", "NL", "Limburg", "province"),
    ("NL-NB", "NL", "North Brabant", "province"), ("NL-NH", "NL", "North Holland", "province"),
    ("NL-OV", "NL", "Overijssel", "province"), ("NL-ZH", "NL", "South Holland", "province"),
    ("NL-UT", "NL", "Utrecht", "province"), ("NL-ZE", "NL", "Zeeland", "province"),
    # Belgium
    ("BE-BRU", "BE", "Brussels", "region"), ("BE-VLG", "BE", "Flanders", "region"),
    ("BE-WAL", "BE", "Wallonia", "region"),
    # Switzerland
    ("CH-AG", "CH", "Aargau", "canton"), ("CH-AI", "CH", "Appenzell Innerrhoden", "canton"),
    ("CH-AR", "CH", "Appenzell Ausserrhoden", "canton"), ("CH-BE", "CH", "Bern", "canton"),
    ("CH-BL", "CH", "Basel-Landschaft", "canton"), ("CH-BS", "CH", "Basel-Stadt", "canton"),
    ("CH-FR", "CH", "Fribourg", "canton"), ("CH-GE", "CH", "Geneva", "canton"),
    ("CH-GL", "CH", "Glarus", "canton"), ("CH-GR", "CH", "Graubunden", "canton"),
    ("CH-JU", "CH", "Jura", "canton"), ("CH-LU", "CH", "Lucerne", "canton"),
    ("CH-NE", "CH", "Neuchatel", "canton"), ("CH-NW", "CH", "Nidwalden", "canton"),
    ("CH-OW", "CH", "Obwalden", "canton"), ("CH-SG", "CH", "St. Gallen", "canton"),
    ("CH-SH", "CH", "Schaffhausen", "canton"), ("CH-SZ", "CH", "Schwyz", "canton"),
    ("CH-SO", "CH", "Solothurn", "canton"), ("CH-TG", "CH", "Thurgau", "canton"),
    ("CH-TI", "CH", "Ticino", "canton"), ("CH-UR", "CH", "Uri", "canton"),
    ("CH-VD", "CH", "Vaud", "canton"), ("CH-VS", "CH", "Valais", "canton"),
    ("CH-ZG", "CH", "Zug", "canton"), ("CH-ZH", "CH", "Zurich", "canton"),
    # Austria
    ("AT-1", "AT", "Burgenland", "state"), ("AT-2", "AT", "Carinthia", "state"),
    ("AT-3", "AT", "Lower Austria", "state"), ("AT-4", "AT", "Upper Austria", "state"),
    ("AT-5", "AT", "Salzburg", "state"), ("AT-6", "AT", "Styria", "state"),
    ("AT-7", "AT", "Tyrol", "state"), ("AT-8", "AT", "Vorarlberg", "state"),
    ("AT-9", "AT", "Vienna", "state"),
    # Poland
    ("PL-02", "PL", "Lower Silesian", "voivodeship"), ("PL-04", "PL", "Kuyavian-Pomeranian", "voivodeship"),
    ("PL-06", "PL", "Lodz", "voivodeship"), ("PL-08", "PL", "Lublin", "voivodeship"),
    ("PL-10", "PL", "Lubusz", "voivodeship"), ("PL-12", "PL", "Lesser Poland", "voivodeship"),
    ("PL-14", "PL", "Masovian", "voivodeship"), ("PL-16", "PL", "Opole", "voivodeship"),
    ("PL-18", "PL", "Subcarpathian", "voivodeship"), ("PL-20", "PL", "Podlaskie", "voivodeship"),
    ("PL-22", "PL", "Pomeranian", "voivodeship"), ("PL-24", "PL", "Silesian", "voivodeship"),
    ("PL-26", "PL", "Holy Cross", "voivodeship"), ("PL-28", "PL", "Warmian-Masurian", "voivodeship"),
    ("PL-30", "PL", "Greater Poland", "voivodeship"), ("PL-32", "PL", "West Pomeranian", "voivodeship"),
    # Sweden
    ("SE-AB", "SE", "Stockholm", "county"), ("SE-AC", "SE", "Vasterbotten", "county"),
    ("SE-BD", "SE", "Norrbotten", "county"), ("SE-C", "SE", "Uppsala", "county"),
    ("SE-D", "SE", "Sodermanland", "county"), ("SE-E", "SE", "Ostergotland", "county"),
    ("SE-F", "SE", "Jonkoping", "county"), ("SE-G", "SE", "Kronoberg", "county"),
    ("SE-H", "SE", "Kalmar", "county"), ("SE-I", "SE", "Gotland", "county"),
    ("SE-K", "SE", "Blekinge", "county"), ("SE-M", "SE", "Skane", "county"),
    ("SE-N", "SE", "Halland", "county"), ("SE-O", "SE", "Vastra Gotaland", "county"),
    ("SE-S", "SE", "Varmland", "county"), ("SE-T", "SE", "Orebro", "county"),
    ("SE-U", "SE", "Vastmanland", "county"), ("SE-W", "SE", "Dalarna", "county"),
    ("SE-X", "SE", "Gavleborg", "county"), ("SE-Y", "SE", "Vasternorrland", "county"),
    ("SE-Z", "SE", "Jamtland", "county"),
    # Norway
    ("NO-03", "NO", "Oslo", "county"), ("NO-11", "NO", "Rogaland", "county"),
    ("NO-15", "NO", "More og Romsdal", "county"), ("NO-18", "NO", "Nordland", "county"),
    ("NO-30", "NO", "Viken", "county"), ("NO-34", "NO", "Innlandet", "county"),
    ("NO-38", "NO", "Vestfold og Telemark", "county"), ("NO-42", "NO", "Agder", "county"),
    ("NO-46", "NO", "Vestland", "county"), ("NO-50", "NO", "Trondelag", "county"),
    ("NO-54", "NO", "Troms og Finnmark", "county"),
    # Denmark
    ("DK-81", "DK", "North Denmark", "region"), ("DK-82", "DK", "Central Denmark", "region"),
    ("DK-83", "DK", "Southern Denmark", "region"), ("DK-84", "DK", "Capital", "region"),
    ("DK-85", "DK", "Zealand", "region"),
    # Finland
    ("FI-01", "FI", "Aland", "region"), ("FI-02", "FI", "South Karelia", "region"),
    ("FI-03", "FI", "South Ostrobothnia", "region"), ("FI-04", "FI", "South Savo", "region"),
    ("FI-05", "FI", "Tavastia Proper", "region"), ("FI-06", "FI", "Central Finland", "region"),
    ("FI-07", "FI", "Central Ostrobothnia", "region"), ("FI-08", "FI", "Kymenlaakso", "region"),
    ("FI-09", "FI", "Lapland", "region"), ("FI-10", "FI", "Pirkanmaa", "region"),
    ("FI-11", "FI", "Ostrobothnia", "region"), ("FI-12", "FI", "North Karelia", "region"),
    ("FI-13", "FI", "North Ostrobothnia", "region"), ("FI-14", "FI", "North Savo", "region"),
    ("FI-15", "FI", "Paijat-Hame", "region"), ("FI-16", "FI", "Satakunta", "region"),
    ("FI-17", "FI", "Uusimaa", "region"), ("FI-18", "FI", "Finland Proper", "region"),
    # Portugal
    ("PT-01", "PT", "Aveiro", "district"), ("PT-02", "PT", "Beja", "district"),
    ("PT-03", "PT", "Braga", "district"), ("PT-04", "PT", "Braganca", "district"),
    ("PT-05", "PT", "Castelo Branco", "district"), ("PT-06", "PT", "Coimbra", "district"),
    ("PT-07", "PT", "Evora", "district"), ("PT-08", "PT", "Faro", "district"),
    ("PT-09", "PT", "Guarda", "district"), ("PT-10", "PT", "Leiria", "district"),
    ("PT-11", "PT", "Lisboa", "district"), ("PT-12", "PT", "Portalegre", "district"),
    ("PT-13", "PT", "Porto", "district"), ("PT-14", "PT", "Santarem", "district"),
    ("PT-15", "PT", "Setubal", "district"), ("PT-16", "PT", "Viana do Castelo", "district"),
    ("PT-17", "PT", "Vila Real", "district"), ("PT-18", "PT", "Viseu", "district"),
    ("PT-20", "PT", "Azores", "autonomous region"), ("PT-30", "PT", "Madeira", "autonomous region"),
    # South Korea
    ("KR-11", "KR", "Seoul", "special city"), ("KR-26", "KR", "Busan", "metropolitan city"),
    ("KR-27", "KR", "Daegu", "metropolitan city"), ("KR-28", "KR", "Incheon", "metropolitan city"),
    ("KR-29", "KR", "Gwangju", "metropolitan city"), ("KR-30", "KR", "Daejeon", "metropolitan city"),
    ("KR-31", "KR", "Ulsan", "metropolitan city"), ("KR-41", "KR", "Gyeonggi", "province"),
    ("KR-42", "KR", "Gangwon", "province"), ("KR-43", "KR", "North Chungcheong", "province"),
    ("KR-44", "KR", "South Chungcheong", "province"), ("KR-45", "KR", "North Jeolla", "province"),
    ("KR-46", "KR", "South Jeolla", "province"), ("KR-47", "KR", "North Gyeongsang", "province"),
    ("KR-48", "KR", "South Gyeongsang", "province"), ("KR-49", "KR", "Jeju", "special self-governing province"),
    ("KR-50", "KR", "Sejong", "special self-governing city"),
    # United Arab Emirates
    ("AE-AZ", "AE", "Abu Dhabi", "emirate"), ("AE-AJ", "AE", "Ajman", "emirate"),
    ("AE-FU", "AE", "Fujairah", "emirate"), ("AE-SH", "AE", "Sharjah", "emirate"),
    ("AE-DU", "AE", "Dubai", "emirate"), ("AE-RK", "AE", "Ras al-Khaimah", "emirate"),
    ("AE-UQ", "AE", "Umm al-Qaiwain", "emirate"),
    # Saudi Arabia
    ("SA-01", "SA", "Riyadh", "region"), ("SA-02", "SA", "Makkah", "region"),
    ("SA-03", "SA", "Medina", "region"), ("SA-04", "SA", "Eastern Province", "region"),
    ("SA-05", "SA", "Aseer", "region"), ("SA-06", "SA", "Tabuk", "region"),
    ("SA-07", "SA", "Hail", "region"), ("SA-08", "SA", "Northern Borders", "region"),
    ("SA-09", "SA", "Jazan", "region"), ("SA-10", "SA", "Najran", "region"),
    ("SA-11", "SA", "Al Bahah", "region"), ("SA-12", "SA", "Al Jawf", "region"),
    ("SA-14", "SA", "Qassim", "region"),
    # Israel
    ("IL-D", "IL", "South", "district"), ("IL-HA", "IL", "Haifa", "district"),
    ("IL-JM", "IL", "Jerusalem", "district"), ("IL-M", "IL", "Central", "district"),
    ("IL-N", "IL", "North", "district"), ("IL-TA", "IL", "Tel Aviv", "district"),
    # Nigeria
    ("NG-AB", "NG", "Abia", "state"), ("NG-FC", "NG", "Abuja", "federal capital territory"),
    ("NG-AD", "NG", "Adamawa", "state"), ("NG-AK", "NG", "Akwa Ibom", "state"),
    ("NG-AN", "NG", "Anambra", "state"), ("NG-BA", "NG", "Bauchi", "state"),
    ("NG-BY", "NG", "Bayelsa", "state"), ("NG-BE", "NG", "Benue", "state"),
    ("NG-BO", "NG", "Borno", "state"), ("NG-CR", "NG", "Cross River", "state"),
    ("NG-DE", "NG", "Delta", "state"), ("NG-EB", "NG", "Ebonyi", "state"),
    ("NG-ED", "NG", "Edo", "state"), ("NG-EK", "NG", "Ekiti", "state"),
    ("NG-EN", "NG", "Enugu", "state"), ("NG-GO", "NG", "Gombe", "state"),
    ("NG-IM", "NG", "Imo", "state"), ("NG-JI", "NG", "Jigawa", "state"),
    ("NG-KD", "NG", "Kaduna", "state"), ("NG-KN", "NG", "Kano", "state"),
    ("NG-KT", "NG", "Katsina", "state"), ("NG-KE", "NG", "Kebbi", "state"),
    ("NG-KO", "NG", "Kogi", "state"), ("NG-KW", "NG", "Kwara", "state"),
    ("NG-LA", "NG", "Lagos", "state"), ("NG-NA", "NG", "Nasarawa", "state"),
    ("NG-NI", "NG", "Niger", "state"), ("NG-OG", "NG", "Ogun", "state"),
    ("NG-ON", "NG", "Ondo", "state"), ("NG-OS", "NG", "Osun", "state"),
    ("NG-OY", "NG", "Oyo", "state"), ("NG-PL", "NG", "Plateau", "state"),
    ("NG-RI", "NG", "Rivers", "state"), ("NG-SO", "NG", "Sokoto", "state"),
    ("NG-TA", "NG", "Taraba", "state"), ("NG-YO", "NG", "Yobe", "state"),
    ("NG-ZA", "NG", "Zamfara", "state"),
    # Colombia
    ("CO-AMA", "CO", "Amazonas", "department"), ("CO-ANT", "CO", "Antioquia", "department"),
    ("CO-ARA", "CO", "Arauca", "department"), ("CO-ATL", "CO", "Atlantico", "department"),
    ("CO-BOL", "CO", "Bolivar", "department"), ("CO-BOY", "CO", "Boyaca", "department"),
    ("CO-CAL", "CO", "Caldas", "department"), ("CO-CAQ", "CO", "Caqueta", "department"),
    ("CO-CAS", "CO", "Casanare", "department"), ("CO-CAU", "CO", "Cauca", "department"),
    ("CO-CES", "CO", "Cesar", "department"), ("CO-CHO", "CO", "Choco", "department"),
    ("CO-COR", "CO", "Cordoba", "department"), ("CO-CUN", "CO", "Cundinamarca", "department"),
    ("CO-DC", "CO", "Bogota", "capital district"), ("CO-GUA", "CO", "Guainia", "department"),
    ("CO-GUV", "CO", "Guaviare", "department"), ("CO-HUI", "CO", "Huila", "department"),
    ("CO-LAG", "CO", "La Guajira", "department"), ("CO-MAG", "CO", "Magdalena", "department"),
    ("CO-MET", "CO", "Meta", "department"), ("CO-NAR", "CO", "Narino", "department"),
    ("CO-NSA", "CO", "Norte de Santander", "department"), ("CO-PUT", "CO", "Putumayo", "department"),
    ("CO-QUI", "CO", "Quindio", "department"), ("CO-RIS", "CO", "Risaralda", "department"),
    ("CO-SAP", "CO", "San Andres", "department"), ("CO-SAN", "CO", "Santander", "department"),
    ("CO-SUC", "CO", "Sucre", "department"), ("CO-TOL", "CO", "Tolima", "department"),
    ("CO-VAC", "CO", "Valle del Cauca", "department"), ("CO-VAU", "CO", "Vaupes", "department"),
    ("CO-VID", "CO", "Vichada", "department"),
    # Chile
    ("CL-AI", "CL", "Aysen", "region"), ("CL-AN", "CL", "Antofagasta", "region"),
    ("CL-AP", "CL", "Arica y Parinacota", "region"), ("CL-AR", "CL", "Araucania", "region"),
    ("CL-AT", "CL", "Atacama", "region"), ("CL-BI", "CL", "Biobio", "region"),
    ("CL-CO", "CL", "Coquimbo", "region"), ("CL-LI", "CL", "O'Higgins", "region"),
    ("CL-LL", "CL", "Los Lagos", "region"), ("CL-LR", "CL", "Los Rios", "region"),
    ("CL-MA", "CL", "Magallanes", "region"), ("CL-ML", "CL", "Maule", "region"),
    ("CL-NB", "CL", "Nuble", "region"), ("CL-RM", "CL", "Santiago Metropolitan", "region"),
    ("CL-TA", "CL", "Tarapaca", "region"), ("CL-VS", "CL", "Valparaiso", "region"),
    # Ukraine
    ("UA-05", "UA", "Vinnytsia", "oblast"), ("UA-07", "UA", "Volyn", "oblast"),
    ("UA-09", "UA", "Luhansk", "oblast"), ("UA-12", "UA", "Dnipropetrovsk", "oblast"),
    ("UA-14", "UA", "Donetsk", "oblast"), ("UA-18", "UA", "Zhytomyr", "oblast"),
    ("UA-21", "UA", "Zakarpattia", "oblast"), ("UA-23", "UA", "Zaporizhzhia", "oblast"),
    ("UA-26", "UA", "Ivano-Frankivsk", "oblast"), ("UA-30", "UA", "Kyiv City", "city"),
    ("UA-32", "UA", "Kyiv", "oblast"), ("UA-35", "UA", "Kirovohrad", "oblast"),
    ("UA-46", "UA", "Lviv", "oblast"), ("UA-48", "UA", "Mykolaiv", "oblast"),
    ("UA-51", "UA", "Odessa", "oblast"), ("UA-53", "UA", "Poltava", "oblast"),
    ("UA-56", "UA", "Rivne", "oblast"), ("UA-59", "UA", "Sumy", "oblast"),
    ("UA-61", "UA", "Ternopil", "oblast"), ("UA-63", "UA", "Kharkiv", "oblast"),
    ("UA-65", "UA", "Kherson", "oblast"), ("UA-68", "UA", "Khmelnytskyi", "oblast"),
    ("UA-71", "UA", "Cherkasy", "oblast"), ("UA-74", "UA", "Chernivtsi", "oblast"),
    ("UA-77", "UA", "Chernihiv", "oblast"),
    # Malaysia
    ("MY-01", "MY", "Johor", "state"), ("MY-02", "MY", "Kedah", "state"),
    ("MY-03", "MY", "Kelantan", "state"), ("MY-04", "MY", "Malacca", "state"),
    ("MY-05", "MY", "Negeri Sembilan", "state"), ("MY-06", "MY", "Pahang", "state"),
    ("MY-07", "MY", "Penang", "state"), ("MY-08", "MY", "Perak", "state"),
    ("MY-09", "MY", "Perlis", "state"), ("MY-10", "MY", "Selangor", "state"),
    ("MY-11", "MY", "Terengganu", "state"), ("MY-12", "MY", "Sabah", "state"),
    ("MY-13", "MY", "Sarawak", "state"), ("MY-14", "MY", "Kuala Lumpur", "federal territory"),
    ("MY-15", "MY", "Labuan", "federal territory"), ("MY-16", "MY", "Putrajaya", "federal territory"),
    # Indonesia
    ("ID-AC", "ID", "Aceh", "province"), ("ID-BA", "ID", "Bali", "province"),
    ("ID-BB", "ID", "Bangka Belitung", "province"), ("ID-BT", "ID", "Banten", "province"),
    ("ID-BE", "ID", "Bengkulu", "province"), ("ID-GO", "ID", "Gorontalo", "province"),
    ("ID-JK", "ID", "Jakarta", "special capital region"), ("ID-JA", "ID", "Jambi", "province"),
    ("ID-JB", "ID", "West Java", "province"), ("ID-JI", "ID", "East Java", "province"),
    ("ID-JT", "ID", "Central Java", "province"), ("ID-JY", "ID", "Yogyakarta", "special region"),
    ("ID-KB", "ID", "West Kalimantan", "province"), ("ID-KI", "ID", "East Kalimantan", "province"),
    ("ID-KR", "ID", "Riau Islands", "province"), ("ID-KS", "ID", "South Kalimantan", "province"),
    ("ID-KT", "ID", "Central Kalimantan", "province"), ("ID-KU", "ID", "North Kalimantan", "province"),
    ("ID-LA", "ID", "Lampung", "province"), ("ID-MA", "ID", "Maluku", "province"),
    ("ID-MU", "ID", "North Maluku", "province"), ("ID-NB", "ID", "West Nusa Tenggara", "province"),
    ("ID-NT", "ID", "East Nusa Tenggara", "province"), ("ID-PA", "ID", "Papua", "province"),
    ("ID-PB", "ID", "West Papua", "province"), ("ID-RI", "ID", "Riau", "province"),
    ("ID-SA", "ID", "North Sulawesi", "province"), ("ID-SB", "ID", "West Sumatra", "province"),
    ("ID-SE", "ID", "Southeast Sulawesi", "province"), ("ID-SN", "ID", "South Sulawesi", "province"),
    ("ID-SR", "ID", "West Sulawesi", "province"), ("ID-SS", "ID", "South Sumatra", "province"),
    ("ID-ST", "ID", "Central Sulawesi", "province"), ("ID-SU", "ID", "North Sumatra", "province"),
    # Pakistan
    ("PK-BA", "PK", "Balochistan", "province"), ("PK-GB", "PK", "Gilgit-Baltistan", "territory"),
    ("PK-IS", "PK", "Islamabad", "federal territory"), ("PK-JK", "PK", "Azad Kashmir", "territory"),
    ("PK-KP", "PK", "Khyber Pakhtunkhwa", "province"), ("PK-PB", "PK", "Punjab", "province"),
    ("PK-SD", "PK", "Sindh", "province"),
    # Egypt
    ("EG-ALX", "EG", "Alexandria", "governorate"), ("EG-ASN", "EG", "Aswan", "governorate"),
    ("EG-AST", "EG", "Asyut", "governorate"), ("EG-BA", "EG", "Red Sea", "governorate"),
    ("EG-BH", "EG", "Beheira", "governorate"), ("EG-BNS", "EG", "Beni Suef", "governorate"),
    ("EG-C", "EG", "Cairo", "governorate"), ("EG-DK", "EG", "Dakahlia", "governorate"),
    ("EG-DT", "EG", "Damietta", "governorate"), ("EG-FYM", "EG", "Faiyum", "governorate"),
    ("EG-GH", "EG", "Gharbia", "governorate"), ("EG-GZ", "EG", "Giza", "governorate"),
    ("EG-IS", "EG", "Ismailia", "governorate"), ("EG-JS", "EG", "South Sinai", "governorate"),
    ("EG-KB", "EG", "Qalyubia", "governorate"), ("EG-KFS", "EG", "Kafr el-Sheikh", "governorate"),
    ("EG-KN", "EG", "Qena", "governorate"), ("EG-LX", "EG", "Luxor", "governorate"),
    ("EG-MN", "EG", "Minya", "governorate"), ("EG-MNF", "EG", "Monufia", "governorate"),
    ("EG-MT", "EG", "Matruh", "governorate"), ("EG-PTS", "EG", "Port Said", "governorate"),
    ("EG-SHG", "EG", "Sohag", "governorate"), ("EG-SHR", "EG", "Sharqia", "governorate"),
    ("EG-SIN", "EG", "North Sinai", "governorate"), ("EG-SUZ", "EG", "Suez", "governorate"),
    ("EG-WAD", "EG", "New Valley", "governorate"),
    # Peru
    ("PE-AMA", "PE", "Amazonas", "region"), ("PE-ANC", "PE", "Ancash", "region"),
    ("PE-APU", "PE", "Apurimac", "region"), ("PE-ARE", "PE", "Arequipa", "region"),
    ("PE-AYA", "PE", "Ayacucho", "region"), ("PE-CAJ", "PE", "Cajamarca", "region"),
    ("PE-CAL", "PE", "Callao", "constitutional province"),
    ("PE-CUS", "PE", "Cusco", "region"), ("PE-HUC", "PE", "Huanuco", "region"),
    ("PE-HUV", "PE", "Huancavelica", "region"), ("PE-ICA", "PE", "Ica", "region"),
    ("PE-JUN", "PE", "Junin", "region"), ("PE-LAL", "PE", "La Libertad", "region"),
    ("PE-LAM", "PE", "Lambayeque", "region"), ("PE-LIM", "PE", "Lima", "region"),
    ("PE-LOR", "PE", "Loreto", "region"), ("PE-MDD", "PE", "Madre de Dios", "region"),
    ("PE-MOQ", "PE", "Moquegua", "region"), ("PE-PAS", "PE", "Pasco", "region"),
    ("PE-PIU", "PE", "Piura", "region"), ("PE-PUN", "PE", "Puno", "region"),
    ("PE-SAM", "PE", "San Martin", "region"), ("PE-TAC", "PE", "Tacna", "region"),
    ("PE-TUM", "PE", "Tumbes", "region"), ("PE-UCA", "PE", "Ucayali", "region"),
]
