"""Reference data seed: IANA timezone names."""
from __future__ import annotations

# IANA canonical timezone names (name, utc_region)
# utc_region = first path component, or 'Etc' / 'UTC' for special zones
ISO_TIMEZONES = [
    # Africa
    ("Africa/Abidjan", "Africa"), ("Africa/Accra", "Africa"), ("Africa/Addis_Ababa", "Africa"),
    ("Africa/Algiers", "Africa"), ("Africa/Asmara", "Africa"), ("Africa/Bamako", "Africa"),
    ("Africa/Bangui", "Africa"), ("Africa/Banjul", "Africa"), ("Africa/Bissau", "Africa"),
    ("Africa/Blantyre", "Africa"), ("Africa/Brazzaville", "Africa"), ("Africa/Bujumbura", "Africa"),
    ("Africa/Cairo", "Africa"), ("Africa/Casablanca", "Africa"), ("Africa/Ceuta", "Africa"),
    ("Africa/Conakry", "Africa"), ("Africa/Dakar", "Africa"), ("Africa/Dar_es_Salaam", "Africa"),
    ("Africa/Djibouti", "Africa"), ("Africa/Douala", "Africa"), ("Africa/El_Aaiun", "Africa"),
    ("Africa/Freetown", "Africa"), ("Africa/Gaborone", "Africa"), ("Africa/Harare", "Africa"),
    ("Africa/Johannesburg", "Africa"), ("Africa/Juba", "Africa"), ("Africa/Kampala", "Africa"),
    ("Africa/Khartoum", "Africa"), ("Africa/Kigali", "Africa"), ("Africa/Kinshasa", "Africa"),
    ("Africa/Lagos", "Africa"), ("Africa/Libreville", "Africa"), ("Africa/Lome", "Africa"),
    ("Africa/Luanda", "Africa"), ("Africa/Lubumbashi", "Africa"), ("Africa/Lusaka", "Africa"),
    ("Africa/Malabo", "Africa"), ("Africa/Maputo", "Africa"), ("Africa/Maseru", "Africa"),
    ("Africa/Mbabane", "Africa"), ("Africa/Mogadishu", "Africa"), ("Africa/Monrovia", "Africa"),
    ("Africa/Nairobi", "Africa"), ("Africa/Ndjamena", "Africa"), ("Africa/Niamey", "Africa"),
    ("Africa/Nouakchott", "Africa"), ("Africa/Ouagadougou", "Africa"), ("Africa/Porto-Novo", "Africa"),
    ("Africa/Sao_Tome", "Africa"), ("Africa/Tripoli", "Africa"), ("Africa/Tunis", "Africa"),
    ("Africa/Windhoek", "Africa"),
    # America
    ("America/Adak", "America"), ("America/Anchorage", "America"), ("America/Anguilla", "America"),
    ("America/Antigua", "America"), ("America/Araguaina", "America"),
    ("America/Argentina/Buenos_Aires", "America"), ("America/Argentina/Catamarca", "America"),
    ("America/Argentina/Cordoba", "America"), ("America/Argentina/Jujuy", "America"),
    ("America/Argentina/La_Rioja", "America"), ("America/Argentina/Mendoza", "America"),
    ("America/Argentina/Rio_Gallegos", "America"), ("America/Argentina/Salta", "America"),
    ("America/Argentina/San_Juan", "America"), ("America/Argentina/San_Luis", "America"),
    ("America/Argentina/Tucuman", "America"), ("America/Argentina/Ushuaia", "America"),
    ("America/Aruba", "America"), ("America/Asuncion", "America"), ("America/Atikokan", "America"),
    ("America/Bahia", "America"), ("America/Bahia_Banderas", "America"), ("America/Barbados", "America"),
    ("America/Belem", "America"), ("America/Belize", "America"), ("America/Blanc-Sablon", "America"),
    ("America/Boa_Vista", "America"), ("America/Bogota", "America"), ("America/Boise", "America"),
    ("America/Cambridge_Bay", "America"), ("America/Campo_Grande", "America"), ("America/Cancun", "America"),
    ("America/Caracas", "America"), ("America/Cayenne", "America"), ("America/Cayman", "America"),
    ("America/Chicago", "America"), ("America/Chihuahua", "America"), ("America/Costa_Rica", "America"),
    ("America/Creston", "America"), ("America/Cuiaba", "America"), ("America/Curacao", "America"),
    ("America/Danmarkshavn", "America"), ("America/Dawson", "America"), ("America/Dawson_Creek", "America"),
    ("America/Denver", "America"), ("America/Detroit", "America"), ("America/Dominica", "America"),
    ("America/Edmonton", "America"), ("America/Eirunepe", "America"), ("America/El_Salvador", "America"),
    ("America/Fortaleza", "America"), ("America/Glace_Bay", "America"), ("America/Goose_Bay", "America"),
    ("America/Grand_Turk", "America"), ("America/Grenada", "America"), ("America/Guadeloupe", "America"),
    ("America/Guatemala", "America"), ("America/Guayaquil", "America"), ("America/Guyana", "America"),
    ("America/Halifax", "America"), ("America/Havana", "America"), ("America/Hermosillo", "America"),
    ("America/Indiana/Indianapolis", "America"), ("America/Indiana/Knox", "America"),
    ("America/Indiana/Marengo", "America"), ("America/Indiana/Petersburg", "America"),
    ("America/Indiana/Tell_City", "America"), ("America/Indiana/Vevay", "America"),
    ("America/Indiana/Vincennes", "America"), ("America/Indiana/Winamac", "America"),
    ("America/Inuvik", "America"), ("America/Iqaluit", "America"), ("America/Jamaica", "America"),
    ("America/Juneau", "America"), ("America/Kentucky/Louisville", "America"),
    ("America/Kentucky/Monticello", "America"), ("America/Kralendijk", "America"),
    ("America/La_Paz", "America"), ("America/Lima", "America"), ("America/Los_Angeles", "America"),
    ("America/Lower_Princes", "America"), ("America/Maceio", "America"), ("America/Managua", "America"),
    ("America/Manaus", "America"), ("America/Marigot", "America"), ("America/Martinique", "America"),
    ("America/Matamoros", "America"), ("America/Mazatlan", "America"), ("America/Menominee", "America"),
    ("America/Merida", "America"), ("America/Metlakatla", "America"), ("America/Mexico_City", "America"),
    ("America/Miquelon", "America"), ("America/Moncton", "America"), ("America/Monterrey", "America"),
    ("America/Montevideo", "America"), ("America/Montserrat", "America"), ("America/Nassau", "America"),
    ("America/New_York", "America"), ("America/Nipigon", "America"), ("America/Nome", "America"),
    ("America/Noronha", "America"), ("America/North_Dakota/Beulah", "America"),
    ("America/North_Dakota/Center", "America"), ("America/North_Dakota/New_Salem", "America"),
    ("America/Nuuk", "America"), ("America/Ojinaga", "America"), ("America/Panama", "America"),
    ("America/Pangnirtung", "America"), ("America/Paramaribo", "America"), ("America/Phoenix", "America"),
    ("America/Port-au-Prince", "America"), ("America/Port_of_Spain", "America"),
    ("America/Porto_Velho", "America"), ("America/Puerto_Rico", "America"),
    ("America/Punta_Arenas", "America"), ("America/Rainy_River", "America"),
    ("America/Rankin_Inlet", "America"), ("America/Recife", "America"), ("America/Regina", "America"),
    ("America/Resolute", "America"), ("America/Rio_Branco", "America"), ("America/Santa_Isabel", "America"),
    ("America/Santarem", "America"), ("America/Santiago", "America"), ("America/Santo_Domingo", "America"),
    ("America/Sao_Paulo", "America"), ("America/Scoresbysund", "America"), ("America/Sitka", "America"),
    ("America/St_Barthelemy", "America"), ("America/St_Johns", "America"), ("America/St_Kitts", "America"),
    ("America/St_Lucia", "America"), ("America/St_Thomas", "America"), ("America/St_Vincent", "America"),
    ("America/Swift_Current", "America"), ("America/Tegucigalpa", "America"), ("America/Thule", "America"),
    ("America/Thunder_Bay", "America"), ("America/Tijuana", "America"), ("America/Toronto", "America"),
    ("America/Tortola", "America"), ("America/Vancouver", "America"), ("America/Whitehorse", "America"),
    ("America/Winnipeg", "America"), ("America/Yakutat", "America"), ("America/Yellowknife", "America"),
    # Antarctica
    ("Antarctica/Casey", "Antarctica"), ("Antarctica/Davis", "Antarctica"),
    ("Antarctica/DumontDUrville", "Antarctica"), ("Antarctica/Macquarie", "Antarctica"),
    ("Antarctica/Mawson", "Antarctica"), ("Antarctica/McMurdo", "Antarctica"),
    ("Antarctica/Palmer", "Antarctica"), ("Antarctica/Rothera", "Antarctica"),
    ("Antarctica/Syowa", "Antarctica"), ("Antarctica/Troll", "Antarctica"),
    ("Antarctica/Vostok", "Antarctica"),
    # Arctic
    ("Arctic/Longyearbyen", "Arctic"),
    # Asia
    ("Asia/Aden", "Asia"), ("Asia/Almaty", "Asia"), ("Asia/Amman", "Asia"),
    ("Asia/Anadyr", "Asia"), ("Asia/Aqtau", "Asia"), ("Asia/Aqtobe", "Asia"),
    ("Asia/Ashgabat", "Asia"), ("Asia/Atyrau", "Asia"), ("Asia/Baghdad", "Asia"),
    ("Asia/Bahrain", "Asia"), ("Asia/Baku", "Asia"), ("Asia/Bangkok", "Asia"),
    ("Asia/Barnaul", "Asia"), ("Asia/Beirut", "Asia"), ("Asia/Bishkek", "Asia"),
    ("Asia/Brunei", "Asia"), ("Asia/Chita", "Asia"), ("Asia/Choibalsan", "Asia"),
    ("Asia/Colombo", "Asia"), ("Asia/Damascus", "Asia"), ("Asia/Dhaka", "Asia"),
    ("Asia/Dili", "Asia"), ("Asia/Dubai", "Asia"), ("Asia/Dushanbe", "Asia"),
    ("Asia/Famagusta", "Asia"), ("Asia/Gaza", "Asia"), ("Asia/Hebron", "Asia"),
    ("Asia/Ho_Chi_Minh", "Asia"), ("Asia/Hong_Kong", "Asia"), ("Asia/Hovd", "Asia"),
    ("Asia/Irkutsk", "Asia"), ("Asia/Jakarta", "Asia"), ("Asia/Jayapura", "Asia"),
    ("Asia/Jerusalem", "Asia"), ("Asia/Kabul", "Asia"), ("Asia/Kamchatka", "Asia"),
    ("Asia/Karachi", "Asia"), ("Asia/Kathmandu", "Asia"), ("Asia/Khandyga", "Asia"),
    ("Asia/Kolkata", "Asia"), ("Asia/Krasnoyarsk", "Asia"), ("Asia/Kuala_Lumpur", "Asia"),
    ("Asia/Kuching", "Asia"), ("Asia/Kuwait", "Asia"), ("Asia/Macau", "Asia"),
    ("Asia/Magadan", "Asia"), ("Asia/Makassar", "Asia"), ("Asia/Manila", "Asia"),
    ("Asia/Muscat", "Asia"), ("Asia/Nicosia", "Asia"), ("Asia/Novokuznetsk", "Asia"),
    ("Asia/Novosibirsk", "Asia"), ("Asia/Omsk", "Asia"), ("Asia/Oral", "Asia"),
    ("Asia/Phnom_Penh", "Asia"), ("Asia/Pontianak", "Asia"), ("Asia/Pyongyang", "Asia"),
    ("Asia/Qatar", "Asia"), ("Asia/Qostanay", "Asia"), ("Asia/Qyzylorda", "Asia"),
    ("Asia/Riyadh", "Asia"), ("Asia/Sakhalin", "Asia"), ("Asia/Samarkand", "Asia"),
    ("Asia/Seoul", "Asia"), ("Asia/Shanghai", "Asia"), ("Asia/Singapore", "Asia"),
    ("Asia/Srednekolymsk", "Asia"), ("Asia/Taipei", "Asia"), ("Asia/Tashkent", "Asia"),
    ("Asia/Tbilisi", "Asia"), ("Asia/Tehran", "Asia"), ("Asia/Thimphu", "Asia"),
    ("Asia/Tokyo", "Asia"), ("Asia/Tomsk", "Asia"), ("Asia/Ulaanbaatar", "Asia"),
    ("Asia/Urumqi", "Asia"), ("Asia/Ust-Nera", "Asia"), ("Asia/Vientiane", "Asia"),
    ("Asia/Vladivostok", "Asia"), ("Asia/Yakutsk", "Asia"), ("Asia/Yangon", "Asia"),
    ("Asia/Yekaterinburg", "Asia"), ("Asia/Yerevan", "Asia"),
    # Atlantic
    ("Atlantic/Azores", "Atlantic"), ("Atlantic/Bermuda", "Atlantic"), ("Atlantic/Canary", "Atlantic"),
    ("Atlantic/Cape_Verde", "Atlantic"), ("Atlantic/Faroe", "Atlantic"), ("Atlantic/Madeira", "Atlantic"),
    ("Atlantic/Reykjavik", "Atlantic"), ("Atlantic/South_Georgia", "Atlantic"),
    ("Atlantic/St_Helena", "Atlantic"), ("Atlantic/Stanley", "Atlantic"),
    # Australia
    ("Australia/Adelaide", "Australia"), ("Australia/Brisbane", "Australia"),
    ("Australia/Broken_Hill", "Australia"), ("Australia/Darwin", "Australia"),
    ("Australia/Eucla", "Australia"), ("Australia/Hobart", "Australia"),
    ("Australia/Lindeman", "Australia"), ("Australia/Lord_Howe", "Australia"),
    ("Australia/Melbourne", "Australia"), ("Australia/Perth", "Australia"),
    ("Australia/Sydney", "Australia"),
    # Europe
    ("Europe/Amsterdam", "Europe"), ("Europe/Andorra", "Europe"), ("Europe/Astrakhan", "Europe"),
    ("Europe/Athens", "Europe"), ("Europe/Belgrade", "Europe"), ("Europe/Berlin", "Europe"),
    ("Europe/Bratislava", "Europe"), ("Europe/Brussels", "Europe"), ("Europe/Bucharest", "Europe"),
    ("Europe/Budapest", "Europe"), ("Europe/Busingen", "Europe"), ("Europe/Chisinau", "Europe"),
    ("Europe/Copenhagen", "Europe"), ("Europe/Dublin", "Europe"), ("Europe/Gibraltar", "Europe"),
    ("Europe/Guernsey", "Europe"), ("Europe/Helsinki", "Europe"), ("Europe/Isle_of_Man", "Europe"),
    ("Europe/Istanbul", "Europe"), ("Europe/Jersey", "Europe"), ("Europe/Kaliningrad", "Europe"),
    ("Europe/Kiev", "Europe"), ("Europe/Kirov", "Europe"), ("Europe/Lisbon", "Europe"),
    ("Europe/Ljubljana", "Europe"), ("Europe/London", "Europe"), ("Europe/Luxembourg", "Europe"),
    ("Europe/Madrid", "Europe"), ("Europe/Malta", "Europe"), ("Europe/Mariehamn", "Europe"),
    ("Europe/Minsk", "Europe"), ("Europe/Monaco", "Europe"), ("Europe/Moscow", "Europe"),
    ("Europe/Nicosia", "Europe"), ("Europe/Oslo", "Europe"), ("Europe/Paris", "Europe"),
    ("Europe/Podgorica", "Europe"), ("Europe/Prague", "Europe"), ("Europe/Riga", "Europe"),
    ("Europe/Rome", "Europe"), ("Europe/Samara", "Europe"), ("Europe/San_Marino", "Europe"),
    ("Europe/Sarajevo", "Europe"), ("Europe/Saratov", "Europe"), ("Europe/Simferopol", "Europe"),
    ("Europe/Skopje", "Europe"), ("Europe/Sofia", "Europe"), ("Europe/Stockholm", "Europe"),
    ("Europe/Tallinn", "Europe"), ("Europe/Tirane", "Europe"), ("Europe/Ulyanovsk", "Europe"),
    ("Europe/Uzhgorod", "Europe"), ("Europe/Vaduz", "Europe"), ("Europe/Vatican", "Europe"),
    ("Europe/Vienna", "Europe"), ("Europe/Vilnius", "Europe"), ("Europe/Volgograd", "Europe"),
    ("Europe/Warsaw", "Europe"), ("Europe/Zagreb", "Europe"), ("Europe/Zaporozhye", "Europe"),
    ("Europe/Zurich", "Europe"),
    # Indian
    ("Indian/Antananarivo", "Indian"), ("Indian/Chagos", "Indian"), ("Indian/Christmas", "Indian"),
    ("Indian/Cocos", "Indian"), ("Indian/Comoro", "Indian"), ("Indian/Kerguelen", "Indian"),
    ("Indian/Mahe", "Indian"), ("Indian/Maldives", "Indian"), ("Indian/Mauritius", "Indian"),
    ("Indian/Mayotte", "Indian"), ("Indian/Reunion", "Indian"),
    # Pacific
    ("Pacific/Apia", "Pacific"), ("Pacific/Auckland", "Pacific"), ("Pacific/Bougainville", "Pacific"),
    ("Pacific/Chatham", "Pacific"), ("Pacific/Chuuk", "Pacific"), ("Pacific/Easter", "Pacific"),
    ("Pacific/Efate", "Pacific"), ("Pacific/Enderbury", "Pacific"), ("Pacific/Fakaofo", "Pacific"),
    ("Pacific/Fiji", "Pacific"), ("Pacific/Funafuti", "Pacific"), ("Pacific/Galapagos", "Pacific"),
    ("Pacific/Gambier", "Pacific"), ("Pacific/Guadalcanal", "Pacific"), ("Pacific/Guam", "Pacific"),
    ("Pacific/Honolulu", "Pacific"), ("Pacific/Kiritimati", "Pacific"), ("Pacific/Kosrae", "Pacific"),
    ("Pacific/Kwajalein", "Pacific"), ("Pacific/Majuro", "Pacific"), ("Pacific/Marquesas", "Pacific"),
    ("Pacific/Midway", "Pacific"), ("Pacific/Nauru", "Pacific"), ("Pacific/Niue", "Pacific"),
    ("Pacific/Norfolk", "Pacific"), ("Pacific/Noumea", "Pacific"), ("Pacific/Pago_Pago", "Pacific"),
    ("Pacific/Palau", "Pacific"), ("Pacific/Pitcairn", "Pacific"), ("Pacific/Pohnpei", "Pacific"),
    ("Pacific/Port_Moresby", "Pacific"), ("Pacific/Rarotonga", "Pacific"), ("Pacific/Saipan", "Pacific"),
    ("Pacific/Tahiti", "Pacific"), ("Pacific/Tarawa", "Pacific"), ("Pacific/Tongatapu", "Pacific"),
    ("Pacific/Wake", "Pacific"), ("Pacific/Wallis", "Pacific"),
    # UTC / Etc
    ("UTC", "UTC"),
    ("Etc/UTC", "Etc"), ("Etc/GMT", "Etc"),
    ("Etc/GMT+1", "Etc"), ("Etc/GMT+2", "Etc"), ("Etc/GMT+3", "Etc"), ("Etc/GMT+4", "Etc"),
    ("Etc/GMT+5", "Etc"), ("Etc/GMT+6", "Etc"), ("Etc/GMT+7", "Etc"), ("Etc/GMT+8", "Etc"),
    ("Etc/GMT+9", "Etc"), ("Etc/GMT+10", "Etc"), ("Etc/GMT+11", "Etc"), ("Etc/GMT+12", "Etc"),
    ("Etc/GMT-1", "Etc"), ("Etc/GMT-2", "Etc"), ("Etc/GMT-3", "Etc"), ("Etc/GMT-4", "Etc"),
    ("Etc/GMT-5", "Etc"), ("Etc/GMT-6", "Etc"), ("Etc/GMT-7", "Etc"), ("Etc/GMT-8", "Etc"),
    ("Etc/GMT-9", "Etc"), ("Etc/GMT-10", "Etc"), ("Etc/GMT-11", "Etc"), ("Etc/GMT-12", "Etc"),
    ("Etc/GMT-13", "Etc"), ("Etc/GMT-14", "Etc"),
]
