"""Reference data seed: ISO 639-1 language codes."""
from __future__ import annotations

CREATE_LANGUAGES_SQL = """
CREATE TABLE IF NOT EXISTS ref_languages (
    alpha2 CHAR(2)      NOT NULL PRIMARY KEY,
    alpha3 CHAR(3)      NOT NULL,
    name   VARCHAR(128) NOT NULL
);
"""

# ISO 639-1 (alpha2, alpha3, name) -- 184 entries
ISO_LANGUAGES = [
    ("ab", "abk", "Abkhazian"), ("aa", "aar", "Afar"), ("af", "afr", "Afrikaans"),
    ("ak", "aka", "Akan"), ("sq", "sqi", "Albanian"), ("am", "amh", "Amharic"),
    ("ar", "ara", "Arabic"), ("an", "arg", "Aragonese"), ("hy", "hye", "Armenian"),
    ("as", "asm", "Assamese"), ("av", "ava", "Avaric"), ("ae", "ave", "Avestan"),
    ("ay", "aym", "Aymara"), ("az", "aze", "Azerbaijani"), ("bm", "bam", "Bambara"),
    ("ba", "bak", "Bashkir"), ("eu", "eus", "Basque"), ("be", "bel", "Belarusian"),
    ("bn", "ben", "Bengali"), ("bh", "bih", "Bihari languages"), ("bi", "bis", "Bislama"),
    ("bs", "bos", "Bosnian"), ("br", "bre", "Breton"), ("bg", "bul", "Bulgarian"),
    ("my", "mya", "Burmese"), ("ca", "cat", "Catalan"), ("km", "khm", "Central Khmer"),
    ("ch", "cha", "Chamorro"), ("ce", "che", "Chechen"), ("ny", "nya", "Chichewa"),
    ("zh", "zho", "Chinese"), ("cu", "chu", "Church Slavic"), ("cv", "chv", "Chuvash"),
    ("kw", "cor", "Cornish"), ("co", "cos", "Corsican"), ("cr", "cre", "Cree"),
    ("hr", "hrv", "Croatian"), ("cs", "ces", "Czech"), ("da", "dan", "Danish"),
    ("dv", "div", "Divehi"), ("nl", "nld", "Dutch"), ("dz", "dzo", "Dzongkha"),
    ("en", "eng", "English"), ("eo", "epo", "Esperanto"), ("et", "est", "Estonian"),
    ("ee", "ewe", "Ewe"), ("fo", "fao", "Faroese"), ("fj", "fij", "Fijian"),
    ("fi", "fin", "Finnish"), ("fr", "fra", "French"), ("ff", "ful", "Fula"),
    ("gl", "glg", "Galician"), ("lg", "lug", "Ganda"), ("ka", "kat", "Georgian"),
    ("de", "deu", "German"), ("el", "ell", "Greek"), ("kl", "kal", "Kalaallisut"),
    ("gn", "grn", "Guarani"), ("gu", "guj", "Gujarati"), ("ht", "hat", "Haitian Creole"),
    ("ha", "hau", "Hausa"), ("he", "heb", "Hebrew"), ("hz", "her", "Herero"),
    ("hi", "hin", "Hindi"), ("ho", "hmo", "Hiri Motu"), ("hu", "hun", "Hungarian"),
    ("is", "isl", "Icelandic"), ("io", "ido", "Ido"), ("ig", "ibo", "Igbo"),
    ("id", "ind", "Indonesian"), ("ia", "ina", "Interlingua"), ("ie", "ile", "Interlingue"),
    ("iu", "iku", "Inuktitut"), ("ik", "ipk", "Inupiaq"), ("ga", "gle", "Irish"),
    ("it", "ita", "Italian"), ("ja", "jpn", "Japanese"), ("jv", "jav", "Javanese"),
    ("kn", "kan", "Kannada"), ("kr", "kau", "Kanuri"), ("ks", "kas", "Kashmiri"),
    ("kk", "kaz", "Kazakh"), ("ki", "kik", "Kikuyu"), ("rw", "kin", "Kinyarwanda"),
    ("ky", "kir", "Kirghiz"), ("kv", "kom", "Komi"), ("kg", "kon", "Kongo"),
    ("ko", "kor", "Korean"), ("kj", "kua", "Kuanyama"), ("ku", "kur", "Kurdish"),
    ("lo", "lao", "Lao"), ("la", "lat", "Latin"), ("lv", "lav", "Latvian"),
    ("li", "lim", "Limburgish"), ("ln", "lin", "Lingala"), ("lt", "lit", "Lithuanian"),
    ("lu", "lub", "Luba-Katanga"), ("lb", "ltz", "Luxembourgish"), ("mk", "mkd", "Macedonian"),
    ("mg", "mlg", "Malagasy"), ("ms", "msa", "Malay"), ("ml", "mal", "Malayalam"),
    ("mt", "mlt", "Maltese"), ("gv", "glv", "Manx"), ("mi", "mri", "Maori"),
    ("mr", "mar", "Marathi"), ("mh", "mah", "Marshallese"), ("mn", "mon", "Mongolian"),
    ("na", "nau", "Nauru"), ("nv", "nav", "Navajo"), ("ng", "ndo", "Ndonga"),
    ("ne", "nep", "Nepali"), ("nd", "nde", "North Ndebele"), ("se", "sme", "Northern Sami"),
    ("no", "nor", "Norwegian"), ("nb", "nob", "Norwegian Bokmal"), ("nn", "nno", "Norwegian Nynorsk"),
    ("oc", "oci", "Occitan"), ("oj", "oji", "Ojibwe"), ("or", "ori", "Oriya"),
    ("om", "orm", "Oromo"), ("os", "oss", "Ossetian"), ("pi", "pli", "Pali"),
    ("pa", "pan", "Panjabi"), ("ps", "pus", "Pashto"), ("fa", "fas", "Persian"),
    ("pl", "pol", "Polish"), ("pt", "por", "Portuguese"), ("qu", "que", "Quechua"),
    ("ro", "ron", "Romanian"), ("rm", "roh", "Romansh"), ("rn", "run", "Rundi"),
    ("ru", "rus", "Russian"), ("sm", "smo", "Samoan"), ("sg", "sag", "Sango"),
    ("sa", "san", "Sanskrit"), ("sc", "srd", "Sardinian"), ("sr", "srp", "Serbian"),
    ("sn", "sna", "Shona"), ("ii", "iii", "Sichuan Yi"), ("sd", "snd", "Sindhi"),
    ("si", "sin", "Sinhala"), ("sk", "slk", "Slovak"), ("sl", "slv", "Slovenian"),
    ("so", "som", "Somali"), ("nr", "nbl", "South Ndebele"), ("st", "sot", "Southern Sotho"),
    ("es", "spa", "Spanish"), ("su", "sun", "Sundanese"), ("sw", "swa", "Swahili"),
    ("ss", "ssw", "Swati"), ("sv", "swe", "Swedish"), ("tl", "tgl", "Tagalog"),
    ("ty", "tah", "Tahitian"), ("tg", "tgk", "Tajik"), ("ta", "tam", "Tamil"),
    ("tt", "tat", "Tatar"), ("te", "tel", "Telugu"), ("th", "tha", "Thai"),
    ("bo", "bod", "Tibetan"), ("ti", "tir", "Tigrinya"), ("to", "ton", "Tonga"),
    ("ts", "tso", "Tsonga"), ("tn", "tsn", "Tswana"), ("tr", "tur", "Turkish"),
    ("tk", "tuk", "Turkmen"), ("tw", "twi", "Twi"), ("ug", "uig", "Uighur"),
    ("uk", "ukr", "Ukrainian"), ("ur", "urd", "Urdu"), ("uz", "uzb", "Uzbek"),
    ("ve", "ven", "Venda"), ("vi", "vie", "Vietnamese"), ("vo", "vol", "Volapuk"),
    ("wa", "wln", "Walloon"), ("cy", "cym", "Welsh"), ("fy", "fry", "Western Frisian"),
    ("wo", "wol", "Wolof"), ("xh", "xho", "Xhosa"), ("yi", "yid", "Yiddish"),
    ("yo", "yor", "Yoruba"), ("za", "zha", "Zhuang"), ("zu", "zul", "Zulu"),
]
