"""Reference data seed: ISO 3166-1 country codes and ISO 4217 currency codes."""
from __future__ import annotations

# ISO 3166-1 alpha-2 country codes (alpha2, alpha3, name)
ISO_COUNTRIES = [
    ("AF", "AFG", "Afghanistan"), ("AL", "ALB", "Albania"), ("DZ", "DZA", "Algeria"),
    ("AD", "AND", "Andorra"), ("AO", "AGO", "Angola"), ("AG", "ATG", "Antigua and Barbuda"),
    ("AR", "ARG", "Argentina"), ("AM", "ARM", "Armenia"), ("AU", "AUS", "Australia"),
    ("AT", "AUT", "Austria"), ("AZ", "AZE", "Azerbaijan"), ("BS", "BHS", "Bahamas"),
    ("BH", "BHR", "Bahrain"), ("BD", "BGD", "Bangladesh"), ("BB", "BRB", "Barbados"),
    ("BY", "BLR", "Belarus"), ("BE", "BEL", "Belgium"), ("BZ", "BLZ", "Belize"),
    ("BJ", "BEN", "Benin"), ("BT", "BTN", "Bhutan"), ("BO", "BOL", "Bolivia"),
    ("BA", "BIH", "Bosnia and Herzegovina"), ("BW", "BWA", "Botswana"), ("BR", "BRA", "Brazil"),
    ("BN", "BRN", "Brunei"), ("BG", "BGR", "Bulgaria"), ("BF", "BFA", "Burkina Faso"),
    ("BI", "BDI", "Burundi"), ("CV", "CPV", "Cabo Verde"), ("KH", "KHM", "Cambodia"),
    ("CM", "CMR", "Cameroon"), ("CA", "CAN", "Canada"), ("CF", "CAF", "Central African Republic"),
    ("TD", "TCD", "Chad"), ("CL", "CHL", "Chile"), ("CN", "CHN", "China"),
    ("CO", "COL", "Colombia"), ("KM", "COM", "Comoros"), ("CG", "COG", "Congo"),
    ("CD", "COD", "Congo (DRC)"), ("CR", "CRI", "Costa Rica"), ("CI", "CIV", "Cote d'Ivoire"),
    ("HR", "HRV", "Croatia"), ("CU", "CUB", "Cuba"), ("CY", "CYP", "Cyprus"),
    ("CZ", "CZE", "Czechia"), ("DK", "DNK", "Denmark"), ("DJ", "DJI", "Djibouti"),
    ("DM", "DMA", "Dominica"), ("DO", "DOM", "Dominican Republic"), ("EC", "ECU", "Ecuador"),
    ("EG", "EGY", "Egypt"), ("SV", "SLV", "El Salvador"), ("GQ", "GNQ", "Equatorial Guinea"),
    ("ER", "ERI", "Eritrea"), ("EE", "EST", "Estonia"), ("SZ", "SWZ", "Eswatini"),
    ("ET", "ETH", "Ethiopia"), ("FJ", "FJI", "Fiji"), ("FI", "FIN", "Finland"),
    ("FR", "FRA", "France"), ("GA", "GAB", "Gabon"), ("GM", "GMB", "Gambia"),
    ("GE", "GEO", "Georgia"), ("DE", "DEU", "Germany"), ("GH", "GHA", "Ghana"),
    ("GR", "GRC", "Greece"), ("GD", "GRD", "Grenada"), ("GT", "GTM", "Guatemala"),
    ("GN", "GIN", "Guinea"), ("GW", "GNB", "Guinea-Bissau"), ("GY", "GUY", "Guyana"),
    ("HT", "HTI", "Haiti"), ("HN", "HND", "Honduras"), ("HU", "HUN", "Hungary"),
    ("IS", "ISL", "Iceland"), ("IN", "IND", "India"), ("ID", "IDN", "Indonesia"),
    ("IR", "IRN", "Iran"), ("IQ", "IRQ", "Iraq"), ("IE", "IRL", "Ireland"),
    ("IL", "ISR", "Israel"), ("IT", "ITA", "Italy"), ("JM", "JAM", "Jamaica"),
    ("JP", "JPN", "Japan"), ("JO", "JOR", "Jordan"), ("KZ", "KAZ", "Kazakhstan"),
    ("KE", "KEN", "Kenya"), ("KI", "KIR", "Kiribati"), ("KW", "KWT", "Kuwait"),
    ("KG", "KGZ", "Kyrgyzstan"), ("LA", "LAO", "Laos"), ("LV", "LVA", "Latvia"),
    ("LB", "LBN", "Lebanon"), ("LS", "LSO", "Lesotho"), ("LR", "LBR", "Liberia"),
    ("LY", "LBY", "Libya"), ("LI", "LIE", "Liechtenstein"), ("LT", "LTU", "Lithuania"),
    ("LU", "LUX", "Luxembourg"), ("MG", "MDG", "Madagascar"), ("MW", "MWI", "Malawi"),
    ("MY", "MYS", "Malaysia"), ("MV", "MDV", "Maldives"), ("ML", "MLI", "Mali"),
    ("MT", "MLT", "Malta"), ("MH", "MHL", "Marshall Islands"), ("MR", "MRT", "Mauritania"),
    ("MU", "MUS", "Mauritius"), ("MX", "MEX", "Mexico"), ("FM", "FSM", "Micronesia"),
    ("MD", "MDA", "Moldova"), ("MC", "MCO", "Monaco"), ("MN", "MNG", "Mongolia"),
    ("ME", "MNE", "Montenegro"), ("MA", "MAR", "Morocco"), ("MZ", "MOZ", "Mozambique"),
    ("MM", "MMR", "Myanmar"), ("NA", "NAM", "Namibia"), ("NR", "NRU", "Nauru"),
    ("NP", "NPL", "Nepal"), ("NL", "NLD", "Netherlands"), ("NZ", "NZL", "New Zealand"),
    ("NI", "NIC", "Nicaragua"), ("NE", "NER", "Niger"), ("NG", "NGA", "Nigeria"),
    ("KP", "PRK", "North Korea"), ("MK", "MKD", "North Macedonia"), ("NO", "NOR", "Norway"),
    ("OM", "OMN", "Oman"), ("PK", "PAK", "Pakistan"), ("PW", "PLW", "Palau"),
    ("PA", "PAN", "Panama"), ("PG", "PNG", "Papua New Guinea"), ("PY", "PRY", "Paraguay"),
    ("PE", "PER", "Peru"), ("PH", "PHL", "Philippines"), ("PL", "POL", "Poland"),
    ("PT", "PRT", "Portugal"), ("QA", "QAT", "Qatar"), ("RO", "ROU", "Romania"),
    ("RU", "RUS", "Russia"), ("RW", "RWA", "Rwanda"), ("KN", "KNA", "Saint Kitts and Nevis"),
    ("LC", "LCA", "Saint Lucia"), ("VC", "VCT", "Saint Vincent and the Grenadines"),
    ("WS", "WSM", "Samoa"), ("SM", "SMR", "San Marino"), ("ST", "STP", "Sao Tome and Principe"),
    ("SA", "SAU", "Saudi Arabia"), ("SN", "SEN", "Senegal"), ("RS", "SRB", "Serbia"),
    ("SC", "SYC", "Seychelles"), ("SL", "SLE", "Sierra Leone"), ("SG", "SGP", "Singapore"),
    ("SK", "SVK", "Slovakia"), ("SI", "SVN", "Slovenia"), ("SB", "SLB", "Solomon Islands"),
    ("SO", "SOM", "Somalia"), ("ZA", "ZAF", "South Africa"), ("SS", "SSD", "South Sudan"),
    ("ES", "ESP", "Spain"), ("LK", "LKA", "Sri Lanka"), ("SD", "SDN", "Sudan"),
    ("SR", "SUR", "Suriname"), ("SE", "SWE", "Sweden"), ("CH", "CHE", "Switzerland"),
    ("SY", "SYR", "Syria"), ("TW", "TWN", "Taiwan"), ("TJ", "TJK", "Tajikistan"),
    ("TZ", "TZA", "Tanzania"), ("TH", "THA", "Thailand"), ("TL", "TLS", "Timor-Leste"),
    ("TG", "TGO", "Togo"), ("TO", "TON", "Tonga"), ("TT", "TTO", "Trinidad and Tobago"),
    ("TN", "TUN", "Tunisia"), ("TR", "TUR", "Turkey"), ("TM", "TKM", "Turkmenistan"),
    ("TV", "TUV", "Tuvalu"), ("UG", "UGA", "Uganda"), ("UA", "UKR", "Ukraine"),
    ("AE", "ARE", "United Arab Emirates"), ("GB", "GBR", "United Kingdom"),
    ("US", "USA", "United States"), ("UY", "URY", "Uruguay"), ("UZ", "UZB", "Uzbekistan"),
    ("VU", "VUT", "Vanuatu"), ("VE", "VEN", "Venezuela"), ("VN", "VNM", "Vietnam"),
    ("YE", "YEM", "Yemen"), ("ZM", "ZMB", "Zambia"), ("ZW", "ZWE", "Zimbabwe"),
]

# ISO 4217 currency codes (code, numeric, name, decimals)
ISO_CURRENCIES = [
    ("AED", 784, "UAE Dirham", 2), ("AFN", 971, "Afghan Afghani", 2),
    ("ALL", 8, "Albanian Lek", 2), ("AMD", 51, "Armenian Dram", 2),
    ("ANG", 532, "Netherlands Antillean Guilder", 2), ("AOA", 973, "Angolan Kwanza", 2),
    ("ARS", 32, "Argentine Peso", 2), ("AUD", 36, "Australian Dollar", 2),
    ("AWG", 533, "Aruban Florin", 2), ("AZN", 944, "Azerbaijani Manat", 2),
    ("BAM", 977, "Bosnia-Herzegovina Convertible Mark", 2), ("BBD", 52, "Barbadian Dollar", 2),
    ("BDT", 50, "Bangladeshi Taka", 2), ("BGN", 975, "Bulgarian Lev", 2),
    ("BHD", 48, "Bahraini Dinar", 3), ("BIF", 108, "Burundian Franc", 0),
    ("BMD", 60, "Bermudan Dollar", 2), ("BND", 96, "Brunei Dollar", 2),
    ("BOB", 68, "Bolivian Boliviano", 2), ("BRL", 986, "Brazilian Real", 2),
    ("BSD", 44, "Bahamian Dollar", 2), ("BTN", 64, "Bhutanese Ngultrum", 2),
    ("BWP", 72, "Botswanan Pula", 2), ("BYN", 933, "Belarusian Ruble", 2),
    ("BZD", 84, "Belize Dollar", 2), ("CAD", 124, "Canadian Dollar", 2),
    ("CDF", 976, "Congolese Franc", 2), ("CHF", 756, "Swiss Franc", 2),
    ("CLP", 152, "Chilean Peso", 0), ("CNY", 156, "Chinese Yuan", 2),
    ("COP", 170, "Colombian Peso", 2), ("CRC", 188, "Costa Rican Colon", 2),
    ("CUP", 192, "Cuban Peso", 2), ("CVE", 132, "Cape Verdean Escudo", 2),
    ("CZK", 203, "Czech Koruna", 2), ("DJF", 262, "Djiboutian Franc", 0),
    ("DKK", 208, "Danish Krone", 2), ("DOP", 214, "Dominican Peso", 2),
    ("DZD", 12, "Algerian Dinar", 2), ("EGP", 818, "Egyptian Pound", 2),
    ("ERN", 232, "Eritrean Nakfa", 2), ("ETB", 230, "Ethiopian Birr", 2),
    ("EUR", 978, "Euro", 2), ("FJD", 242, "Fijian Dollar", 2),
    ("FKP", 238, "Falkland Islands Pound", 2), ("GBP", 826, "British Pound", 2),
    ("GEL", 981, "Georgian Lari", 2), ("GHS", 936, "Ghanaian Cedi", 2),
    ("GIP", 292, "Gibraltar Pound", 2), ("GMD", 270, "Gambian Dalasi", 2),
    ("GNF", 324, "Guinean Franc", 0), ("GTQ", 320, "Guatemalan Quetzal", 2),
    ("GYD", 328, "Guyanaese Dollar", 2), ("HKD", 344, "Hong Kong Dollar", 2),
    ("HNL", 340, "Honduran Lempira", 2), ("HTG", 332, "Haitian Gourde", 2),
    ("HUF", 348, "Hungarian Forint", 2), ("IDR", 360, "Indonesian Rupiah", 2),
    ("ILS", 376, "Israeli New Shekel", 2), ("INR", 356, "Indian Rupee", 2),
    ("IQD", 368, "Iraqi Dinar", 3), ("IRR", 364, "Iranian Rial", 2),
    ("ISK", 352, "Icelandic Krona", 0), ("JMD", 388, "Jamaican Dollar", 2),
    ("JOD", 400, "Jordanian Dinar", 3), ("JPY", 392, "Japanese Yen", 0),
    ("KES", 404, "Kenyan Shilling", 2), ("KGS", 417, "Kyrgystani Som", 2),
    ("KHR", 116, "Cambodian Riel", 2), ("KMF", 174, "Comorian Franc", 0),
    ("KPW", 408, "North Korean Won", 2), ("KRW", 410, "South Korean Won", 0),
    ("KWD", 414, "Kuwaiti Dinar", 3), ("KYD", 136, "Cayman Islands Dollar", 2),
    ("KZT", 398, "Kazakhstani Tenge", 2), ("LAK", 418, "Laotian Kip", 2),
    ("LBP", 422, "Lebanese Pound", 2), ("LKR", 144, "Sri Lankan Rupee", 2),
    ("LRD", 430, "Liberian Dollar", 2), ("LSL", 426, "Lesotho Loti", 2),
    ("LYD", 434, "Libyan Dinar", 3), ("MAD", 504, "Moroccan Dirham", 2),
    ("MDL", 498, "Moldovan Leu", 2), ("MGA", 969, "Malagasy Ariary", 2),
    ("MKD", 807, "Macedonian Denar", 2), ("MMK", 104, "Myanmar Kyat", 2),
    ("MNT", 496, "Mongolian Tugrik", 2), ("MOP", 446, "Macanese Pataca", 2),
    ("MRU", 929, "Mauritanian Ouguiya", 2), ("MUR", 480, "Mauritian Rupee", 2),
    ("MVR", 462, "Maldivian Rufiyaa", 2), ("MWK", 454, "Malawian Kwacha", 2),
    ("MXN", 484, "Mexican Peso", 2), ("MYR", 458, "Malaysian Ringgit", 2),
    ("MZN", 943, "Mozambican Metical", 2), ("NAD", 516, "Namibian Dollar", 2),
    ("NGN", 566, "Nigerian Naira", 2), ("NIO", 558, "Nicaraguan Cordoba", 2),
    ("NOK", 578, "Norwegian Krone", 2), ("NPR", 524, "Nepalese Rupee", 2),
    ("NZD", 554, "New Zealand Dollar", 2), ("OMR", 512, "Omani Rial", 3),
    ("PAB", 590, "Panamanian Balboa", 2), ("PEN", 604, "Peruvian Sol", 2),
    ("PGK", 598, "Papua New Guinean Kina", 2), ("PHP", 608, "Philippine Peso", 2),
    ("PKR", 586, "Pakistani Rupee", 2), ("PLN", 985, "Polish Zloty", 2),
    ("PYG", 600, "Paraguayan Guarani", 0), ("QAR", 634, "Qatari Rial", 2),
    ("RON", 946, "Romanian Leu", 2), ("RSD", 941, "Serbian Dinar", 2),
    ("RUB", 643, "Russian Ruble", 2), ("RWF", 646, "Rwandan Franc", 0),
    ("SAR", 682, "Saudi Riyal", 2), ("SBD", 90, "Solomon Islands Dollar", 2),
    ("SCR", 690, "Seychellois Rupee", 2), ("SDG", 938, "Sudanese Pound", 2),
    ("SEK", 752, "Swedish Krona", 2), ("SGD", 702, "Singapore Dollar", 2),
    ("SHP", 654, "Saint Helena Pound", 2), ("SLE", 925, "Sierra Leonean Leone", 2),
    ("SOS", 706, "Somali Shilling", 2), ("SRD", 968, "Surinamese Dollar", 2),
    ("SSP", 728, "South Sudanese Pound", 2), ("STN", 930, "Sao Tomean Dobra", 2),
    ("SVC", 222, "Salvadoran Colon", 2), ("SYP", 760, "Syrian Pound", 2),
    ("SZL", 748, "Swazi Lilangeni", 2), ("THB", 764, "Thai Baht", 2),
    ("TJS", 972, "Tajikistani Somoni", 2), ("TMT", 934, "Turkmenistan Manat", 2),
    ("TND", 788, "Tunisian Dinar", 3), ("TOP", 776, "Tongan Paanga", 2),
    ("TRY", 949, "Turkish Lira", 2), ("TTD", 780, "Trinidad and Tobago Dollar", 2),
    ("TWD", 901, "New Taiwan Dollar", 2), ("TZS", 834, "Tanzanian Shilling", 2),
    ("UAH", 980, "Ukrainian Hryvnia", 2), ("UGX", 800, "Ugandan Shilling", 0),
    ("USD", 840, "US Dollar", 2), ("UYU", 858, "Uruguayan Peso", 2),
    ("UZS", 860, "Uzbekistan Som", 2), ("VES", 928, "Venezuelan Bolivar Soberano", 2),
    ("VND", 704, "Vietnamese Dong", 0), ("VUV", 548, "Vanuatu Vatu", 0),
    ("WST", 882, "Samoan Tala", 2), ("XAF", 950, "CFA Franc BEAC", 0),
    ("XCD", 951, "East Caribbean Dollar", 2), ("XOF", 952, "CFA Franc BCEAO", 0),
    ("XPF", 953, "CFP Franc", 0), ("YER", 886, "Yemeni Rial", 2),
    ("ZAR", 710, "South African Rand", 2), ("ZMW", 967, "Zambian Kwacha", 2),
    ("ZWL", 932, "Zimbabwean Dollar", 2),
]

CREATE_REF_TABLES_SQL = """
CREATE TABLE IF NOT EXISTS ref_countries (
    alpha2  CHAR(2)      NOT NULL PRIMARY KEY,
    alpha3  CHAR(3)      NOT NULL,
    name    VARCHAR(128) NOT NULL
);

CREATE TABLE IF NOT EXISTS ref_currencies (
    code      CHAR(3)      NOT NULL PRIMARY KEY,
    numeric   SMALLINT     NOT NULL,
    name      VARCHAR(128) NOT NULL,
    decimals  SMALLINT     NOT NULL DEFAULT 2
);
"""
